local DataHelperTests = {}

-- Mirror of ROM's type enum (constants/pokemon.h)
local TYPE_NONE    = 0
local TYPE_NORMAL  = 1
local TYPE_STEEL   = 9
local TYPE_MYSTERY = 10
local TYPE_FIRE    = 11
local TYPE_ICE     = 16
local TYPE_FAIRY   = 19
local TYPE_STELLAR = 20
local NUMBER_OF_MON_TYPES = 21

-- Disallowed types that must never appear as a distorted result.
local DISALLOWED = { [TYPE_NONE] = true, [TYPE_MYSTERY] = true, [TYPE_STELLAR] = true }

-- Same algorithm using 1-indexed arrays, matching the tracker's Lua idiom
-- (DataHelper.lua getDistortedMoveType). Compared against the golden values
-- below, which were generated by the ROM's C implementation using 0-indexed
-- arrays and u32 arithmetic.
local function calcDistortedType(seed, moveId, type1Idx, type2Idx)
    local validTypes = {}
    for i = 0, NUMBER_OF_MON_TYPES - 1 do
        if i ~= TYPE_NONE and i ~= TYPE_MYSTERY and i ~= TYPE_STELLAR
            and i ~= type1Idx and i ~= type2Idx then
            validTypes[#validTypes + 1] = i
        end
    end
    if #validTypes == 0 then return nil end

    local hash = seed
    hash = hash ~ (moveId << 3)
    hash = hash ~ (moveId >> 2)
    hash = (hash + moveId * 37) & 0xFFFFFFFF
    hash = hash ~ (hash >> 8)

    return validTypes[(hash % #validTypes) + 1]
end

-- Golden values generated by compiling and running the ROM's CalcDistortedType
-- (C u32 arithmetic, 0-indexed arrays). Each entry: { seed, moveId, type1, type2, expectedType }
local GOLDEN_VALUES = {
    -- Normal/Normal
    {   0,   1,  1,  1, 14 },
    {   0,  33,  1,  1, 13 },
    {   0,  85,  1,  1,  9 },
    {   0, 100,  1,  1,  3 },
    {   0, 200,  1,  1,  5 },
    {   0, 311,  1,  1,  6 },
    {   0, 400,  1,  1,  8 },
    {   0, 500,  1,  1,  7 },
    {   0, 600,  1,  1,  6 },
    {   0, 800,  1,  1, 16 },
    {   1,   1,  1,  1, 15 },
    {   1,  33,  1,  1, 16 },
    {   1,  85,  1,  1, 11 },
    {   1, 100,  1,  1,  4 },
    {   1, 200,  1,  1,  4 },
    {   1, 311,  1,  1, 11 },
    {   1, 400,  1,  1,  9 },
    {   1, 500,  1,  1,  6 },
    {   1, 600,  1,  1,  5 },
    {   1, 800,  1,  1, 15 },
    {   7,   1,  1,  1,  3 },
    {   7,  33,  1,  1,  4 },
    {   7,  85,  1,  1, 13 },
    {   7, 100,  1,  1, 13 },
    {   7, 200,  1,  1, 11 },
    {   7, 311,  1,  1, 13 },
    {   7, 400,  1,  1, 12 },
    {   7, 500,  1,  1,  7 },
    {   7, 600,  1,  1, 17 },
    {   7, 800,  1,  1, 13 },
    {  42,   1,  1,  1,  5 },
    {  42,  33,  1,  1,  3 },
    {  42,  85,  1,  1, 17 },
    {  42, 100,  1,  1, 17 },
    {  42, 200,  1,  1, 18 },
    {  42, 311,  1,  1, 13 },
    {  42, 400,  1,  1, 17 },
    {  42, 500,  1,  1,  2 },
    {  42, 600,  1,  1, 14 },
    {  42, 800,  1,  1,  5 },
    { 100,   1,  1,  1, 12 },
    { 100,  33,  1,  1,  4 },
    { 100,  85,  1,  1, 12 },
    { 100, 100,  1,  1,  7 },
    { 100, 200,  1,  1, 19 },
    { 100, 311,  1,  1, 14 },
    { 100, 400,  1,  1,  9 },
    { 100, 500,  1,  1,  4 },
    { 100, 600,  1,  1, 16 },
    { 100, 800,  1,  1, 14 },
    { 128,   1,  1,  1,  5 },
    { 128,  33,  1,  1,  7 },
    { 128,  85,  1,  1, 17 },
    { 128, 100,  1,  1, 16 },
    { 128, 200,  1,  1, 15 },
    { 128, 311,  1,  1, 15 },
    { 128, 400,  1,  1, 17 },
    { 128, 500,  1,  1, 13 },
    { 128, 600,  1,  1, 16 },
    { 128, 800,  1,  1,  4 },
    { 200,   1,  1,  1, 11 },
    { 200,  33,  1,  1, 12 },
    { 200,  85,  1,  1,  5 },
    { 200, 100,  1,  1,  3 },
    { 200, 200,  1,  1, 14 },
    { 200, 311,  1,  1, 12 },
    { 200, 400,  1,  1, 19 },
    { 200, 500,  1,  1, 19 },
    { 200, 600,  1,  1, 18 },
    { 200, 800,  1,  1, 17 },
    { 255,   1,  1,  1, 16 },
    { 255,  33,  1,  1, 16 },
    { 255,  85,  1,  1, 14 },
    { 255, 100,  1,  1,  9 },
    { 255, 200,  1,  1,  4 },
    { 255, 311,  1,  1, 18 },
    { 255, 400,  1,  1,  7 },
    { 255, 500,  1,  1,  2 },
    { 255, 600,  1,  1, 14 },
    { 255, 800,  1,  1, 13 },
    -- Ice/Steel
    {   0,   1, 16,  9, 17 },
    {   0,  33, 16,  9,  1 },
    {   0,  85, 16,  9, 12 },
    {   0, 100, 16,  9, 15 },
    {   0, 200, 16,  9, 12 },
    {   0, 311, 16,  9, 18 },
    {   0, 400, 16,  9,  3 },
    {   0, 500, 16,  9, 12 },
    {   0, 600, 16,  9,  8 },
    {   0, 800, 16,  9,  6 },
    {   1,   1, 16,  9, 18 },
    {   1,  33, 16,  9,  4 },
    {   1,  85, 16,  9, 13 },
    {   1, 100, 16,  9, 17 },
    {   1, 200, 16,  9, 11 },
    {   1, 311, 16,  9,  2 },
    {   1, 400, 16,  9,  4 },
    {   1, 500, 16,  9, 11 },
    {   1, 600, 16,  9,  7 },
    {   1, 800, 16,  9,  5 },
    {   7,   1, 16,  9,  5 },
    {   7,  33, 16,  9, 12 },
    {   7,  85, 16,  9, 15 },
    {   7, 100, 16,  9,  4 },
    {   7, 200, 16,  9, 18 },
    {   7, 311, 16,  9,  4 },
    {   7, 400, 16,  9,  6 },
    {   7, 500, 16,  9,  7 },
    {   7, 600, 16,  9,  1 },
    {   7, 800, 16,  9,  3 },
    {  42,   1, 16,  9,  8 },
    {  42,  33, 16,  9, 13 },
    {  42,  85, 16,  9, 18 },
    {  42, 100, 16,  9,  7 },
    {  42, 200, 16,  9,  4 },
    {  42, 311, 16,  9,  5 },
    {  42, 400, 16,  9, 11 },
    {  42, 500, 16,  9,  4 },
    {  42, 600, 16,  9, 17 },
    {  42, 800, 16,  9, 19 },
    { 100,   1, 16,  9,  2 },
    { 100,  33, 16,  9, 19 },
    { 100,  85, 16,  9, 17 },
    { 100, 100, 16,  9,  1 },
    { 100, 200, 16,  9, 15 },
    { 100, 311, 16,  9,  3 },
    { 100, 400, 16,  9,  7 },
    { 100, 500, 16,  9, 13 },
    { 100, 600, 16,  9,  3 },
    { 100, 800, 16,  9,  2 },
    { 128,   1, 16,  9, 17 },
    { 128,  33, 16,  9,  4 },
    { 128,  85, 16,  9, 11 },
    { 128, 100, 16,  9, 19 },
    { 128, 200, 16,  9, 12 },
    { 128, 311, 16,  9, 18 },
    { 128, 400, 16,  9,  3 },
    { 128, 500, 16,  9,  7 },
    { 128, 600, 16,  9,  8 },
    { 128, 800, 16,  9,  5 },
    { 200,   1, 16,  9,  6 },
    { 200,  33, 16,  9, 14 },
    { 200,  85, 16,  9,  1 },
    { 200, 100, 16,  9,  8 },
    { 200, 200, 16,  9,  2 },
    { 200, 311, 16,  9,  7 },
    { 200, 400, 16,  9, 12 },
    { 200, 500, 16,  9, 18 },
    { 200, 600, 16,  9, 19 },
    { 200, 800, 16,  9, 15 },
    { 255,   1, 16,  9, 17 },
    { 255,  33, 16,  9,  3 },
    { 255,  85, 16,  9,  6 },
    { 255, 100, 16,  9, 11 },
    { 255, 200, 16,  9,  7 },
    { 255, 311, 16,  9, 11 },
    { 255, 400, 16,  9, 18 },
    { 255, 500, 16,  9,  2 },
    { 255, 600, 16,  9, 11 },
    { 255, 800, 16,  9, 14 },
    -- Fire/Fairy
    {   0,   1, 11, 19, 16 },
    {   0,  33, 11, 19,  1 },
    {   0,  85, 11, 19, 12 },
    {   0, 100, 11, 19, 15 },
    {   0, 200, 11, 19, 12 },
    {   0, 311, 11, 19, 17 },
    {   0, 400, 11, 19,  3 },
    {   0, 500, 11, 19, 12 },
    {   0, 600, 11, 19,  8 },
    {   0, 800, 11, 19,  6 },
    {   1,   1, 11, 19, 17 },
    {   1,  33, 11, 19,  4 },
    {   1,  85, 11, 19, 13 },
    {   1, 100, 11, 19, 16 },
    {   1, 200, 11, 19,  9 },
    {   1, 311, 11, 19,  2 },
    {   1, 400, 11, 19,  4 },
    {   1, 500, 11, 19,  9 },
    {   1, 600, 11, 19,  7 },
    {   1, 800, 11, 19,  5 },
    {   7,   1, 11, 19,  5 },
    {   7,  33, 11, 19, 12 },
    {   7,  85, 11, 19, 15 },
    {   7, 100, 11, 19,  4 },
    {   7, 200, 11, 19, 17 },
    {   7, 311, 11, 19,  4 },
    {   7, 400, 11, 19,  6 },
    {   7, 500, 11, 19,  7 },
    {   7, 600, 11, 19,  1 },
    {   7, 800, 11, 19,  3 },
    {  42,   1, 11, 19,  8 },
    {  42,  33, 11, 19, 13 },
    {  42,  85, 11, 19, 17 },
    {  42, 100, 11, 19,  7 },
    {  42, 200, 11, 19,  4 },
    {  42, 311, 11, 19,  5 },
    {  42, 400, 11, 19,  9 },
    {  42, 500, 11, 19,  4 },
    {  42, 600, 11, 19, 16 },
    {  42, 800, 11, 19, 18 },
    { 100,   1, 11, 19,  2 },
    { 100,  33, 11, 19, 18 },
    { 100,  85, 11, 19, 16 },
    { 100, 100, 11, 19,  1 },
    { 100, 200, 11, 19, 15 },
    { 100, 311, 11, 19,  3 },
    { 100, 400, 11, 19,  7 },
    { 100, 500, 11, 19, 13 },
    { 100, 600, 11, 19,  3 },
    { 100, 800, 11, 19,  2 },
    { 128,   1, 11, 19, 16 },
    { 128,  33, 11, 19,  4 },
    { 128,  85, 11, 19,  9 },
    { 128, 100, 11, 19, 18 },
    { 128, 200, 11, 19, 12 },
    { 128, 311, 11, 19, 17 },
    { 128, 400, 11, 19,  3 },
    { 128, 500, 11, 19,  7 },
    { 128, 600, 11, 19,  8 },
    { 128, 800, 11, 19,  5 },
    { 200,   1, 11, 19,  6 },
    { 200,  33, 11, 19, 14 },
    { 200,  85, 11, 19,  1 },
    { 200, 100, 11, 19,  8 },
    { 200, 200, 11, 19,  2 },
    { 200, 311, 11, 19,  7 },
    { 200, 400, 11, 19, 12 },
    { 200, 500, 11, 19, 17 },
    { 200, 600, 11, 19, 18 },
    { 200, 800, 11, 19, 15 },
    { 255,   1, 11, 19, 16 },
    { 255,  33, 11, 19,  3 },
    { 255,  85, 11, 19,  6 },
    { 255, 100, 11, 19,  9 },
    { 255, 200, 11, 19,  7 },
    { 255, 311, 11, 19,  9 },
    { 255, 400, 11, 19, 17 },
    { 255, 500, 11, 19,  2 },
    { 255, 600, 11, 19,  9 },
    { 255, 800, 11, 19, 14 },
}

-- Representative move IDs for sweep tests.
local TEST_MOVES = {
    1, 2, 10, 33, 50, 85, 100, 165, 200, 237, 250, 311, 355,
    400, 450, 500, 560, 600, 700, 800,
}

-- Type pair scenarios for sweep tests.
local TYPE_PAIRS = {
    { TYPE_NORMAL, TYPE_NORMAL, "Monotype Normal" },
    { TYPE_ICE,    TYPE_STEEL,  "Dual Ice/Steel" },
    { TYPE_FIRE,   TYPE_FAIRY,  "Dual Fire/Fairy" },
    { TYPE_NORMAL, TYPE_FIRE,   "Dual Normal/Fire" },
}

-- Test: Lua implementation (1-indexed arrays) matches golden values produced by
-- compiling and running the ROM's C CalcDistortedType (0-indexed, u32 arithmetic).
-- 240 data points across 3 type pairs × 8 seeds × 10 moves.
local function testGoldenValues()
    for i, gv in ipairs(GOLDEN_VALUES) do
        local seed, moveId, t1, t2, expected = gv[1], gv[2], gv[3], gv[4], gv[5]
        local result = calcDistortedType(seed, moveId, t1, t2)
        assert(result == expected, string.format(
            "Golden[%d]: seed=%d move=%d types=(%d,%d) expected=%d got=%s",
            i, seed, moveId, t1, t2, expected, tostring(result)))
    end
    return true
end

-- Test: distorted type never produces a disallowed type (NONE, MYSTERY, STELLAR).
-- Sweeps all 256 seeds × 20 moves × 4 type pairs = 20480 iterations.
local function testNoDisallowedTypes()
    for _, pair in ipairs(TYPE_PAIRS) do
        local t1, t2, label = pair[1], pair[2], pair[3]
        for seed = 0, 255 do
            for _, moveId in ipairs(TEST_MOVES) do
                local result = calcDistortedType(seed, moveId, t1, t2)
                assert(result ~= nil, string.format(
                    "%s seed=%d move=%d: got nil", label, seed, moveId))
                assert(not DISALLOWED[result], string.format(
                    "%s seed=%d move=%d: got disallowed type %d", label, seed, moveId, result))
            end
        end
    end
    return true
end

-- Test: distorted type never matches the Pokémon's own types (no STAB).
-- Sweeps all 256 seeds × 20 moves × 4 type pairs = 20480 iterations.
local function testNoStabTypes()
    for _, pair in ipairs(TYPE_PAIRS) do
        local t1, t2, label = pair[1], pair[2], pair[3]
        for seed = 0, 255 do
            for _, moveId in ipairs(TEST_MOVES) do
                local result = calcDistortedType(seed, moveId, t1, t2)
                assert(result ~= t1, string.format(
                    "%s seed=%d move=%d: got own type1 %d", label, seed, moveId, t1))
                assert(result ~= t2, string.format(
                    "%s seed=%d move=%d: got own type2 %d", label, seed, moveId, t2))
            end
        end
    end
    return true
end

-- Test: result is always a valid battle type index (1-19 excluding MYSTERY).
local function testResultInValidRange()
    local VALID = {}
    for i = 0, NUMBER_OF_MON_TYPES - 1 do
        if not DISALLOWED[i] then
            VALID[i] = true
        end
    end

    for seed = 0, 255 do
        for _, moveId in ipairs(TEST_MOVES) do
            local result = calcDistortedType(seed, moveId, TYPE_ICE, TYPE_STEEL)
            assert(VALID[result], string.format(
                "seed=%d move=%d: result %d not in valid type range", seed, moveId, result))
        end
    end
    return true
end

function DataHelperTests.run()
    Utils.printDebug("[TEST] Running DataHelper tests")
    local tests = Roguemon.Tests

    local results = {
        tests.runTest("golden values match ROM C output", testGoldenValues),
        tests.runTest("no disallowed types across 256 seeds", testNoDisallowedTypes),
        tests.runTest("no STAB types across 256 seeds", testNoStabTypes),
        tests.runTest("result in valid type range", testResultInValidRange),
    }

    local allPassed = true
    for _, ok in ipairs(results) do
        if not ok then allPassed = false; break end
    end

    if not allPassed then
        Utils.printDebug("[WARN] DataHelper tests completed with failures")
    else
        Utils.printDebug("[TEST] DataHelper tests passed")
    end
end

return DataHelperTests
