-- AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
-- This file is generated by tools/config-gen/generate-roguemon-tracker-script.py
-- from the GameSettings.j2 template. Edit the template instead.

local RoguemonGameSettings = {
    configAddr = 0x0,
    signature  = "RGMNRGMN",
}

local function readString(offset, len)
    local b = memory.readbyterange(offset, len)
    local s = string.char(table.unpack(b, 0, len - 1))
    return s
end

local function assertPadZero(offset, len, label)
    local bytes = memory.readbyterange(offset, len)
    for i = 0, len - 1 do
        local v = bytes[i] or 0
        assert(v == 0, string.format("%s expected 0 at 0x%08X (+0x%X), found 0x%02X", label or "pad", offset, i, v))
    end
end

function RoguemonGameSettings.findConfigBase()
    for addr = 0x100, 0x210, 4 do
        local ptr = memory.read_u32_le(addr, "ROM")
        if ptr & 0xFE000000 == 0x08000000 then
            local sig = readString(ptr, 8)
            if sig == RoguemonGameSettings.signature then
                return ptr, sig
            end
        end
    end
    return nil, nil
end


function RoguemonGameSettings.loadGameSettings()
    local startAddr, signature = RoguemonGameSettings.findConfigBase()
    assert(signature ~= nil, "Unable to locate RogueMon settings signature")
    assert(signature == RoguemonGameSettings.signature, string.format("Invalid RogueMon signature at 0x%08X", startAddr))

    Utils.printDebug(">> RogueMon settings signature identified at 0x%08X", startAddr)
    RoguemonGameSettings.configAddr = startAddr
    GameSettings.configAddr = startAddr

    GameSettings.roguemonVersionStr = readString(startAddr + 0x08, 0x10)
    GameSettings.roguemonBuildProfile = Memory.readdword(startAddr + 0x18)
    GameSettings.roguemonConfigStamp = Memory.readdword(startAddr + 0x24)

    local expectedConfigStamp = 0x5348E926
    GameSettings.roguemonConfigStampExpected = expectedConfigStamp
    if GameSettings.roguemonConfigStamp ~= expectedConfigStamp then
        error(string.format("RoguemonConfig stamp mismatch: ROM %s, expected 0x%08X", tostring(GameSettings.roguemonConfigStamp), expectedConfigStamp))
    end

    Utils.printDebug(">> RogueMon version is %s", GameSettings.roguemonVersionStr)
    Utils.printDebug("")

    -- Validate padding blocks
    assertPadZero(startAddr + 0x28, 32, "_pad0")
    assertPadZero(startAddr + 0x24C, 32, "_pad1")
    assertPadZero(startAddr + 0x294, 32, "_pad2")
    assertPadZero(startAddr + 0x2F6, 32, "_pad3")
    assertPadZero(startAddr + 0x344, 32, "_pad4")
    assertPadZero(startAddr + 0x376, 32, "_pad5")
    assertPadZero(startAddr + 0x5BA, 20, "_pad6")

    -- Read values from RogueMon config block
    GameSettings.sig1 = Memory.readdword(startAddr + 0x00)
    GameSettings.sig2 = Memory.readdword(startAddr + 0x04)
    GameSettings.roguemonUidStamp = Memory.readdword(startAddr + 0x1C)
    GameSettings.roguemonAscension = Memory.readbyte(startAddr + 0x20)
    GameSettings.roguemonTypeStamp = Memory.readbyte(startAddr + 0x21)
    GameSettings.roguemonConfigStamp = Memory.readdword(startAddr + 0x24)
    GameSettings.dexOrderAddr = Memory.readdword(startAddr + 0x48)
    GameSettings.gSpeciesInfo = Memory.readdword(startAddr + 0x4C)
    GameSettings.gMovesInfo = Memory.readdword(startAddr + 0x50)
    GameSettings.sTMHMLearnsets = Memory.readdword(startAddr + 0x54)
    GameSettings.gTMHMItemMoveIds = Memory.readdword(startAddr + 0x58)
    GameSettings.gTrainers = Memory.readdword(startAddr + 0x5C)
    GameSettings.gTrainerClasses = Memory.readdword(startAddr + 0x60)
    GameSettings.gItemsInfo = Memory.readdword(startAddr + 0x64)
    GameSettings.gAbilitiesInfo = Memory.readdword(startAddr + 0x68)
    GameSettings.gPlayerParty = Memory.readdword(startAddr + 0x6C)
    GameSettings.pstats = Memory.readdword(startAddr + 0x6C)
    GameSettings.gEnemyParty = Memory.readdword(startAddr + 0x70)
    GameSettings.estats = Memory.readdword(startAddr + 0x70)
    GameSettings.gBattleOutcome = Memory.readdword(startAddr + 0x74)
    GameSettings.gBattleResults = Memory.readdword(startAddr + 0x78)
    GameSettings.gBattleStructPtr = Memory.readdword(startAddr + 0x7C)
    GameSettings.gBattleTerrain = Memory.readdword(startAddr + 0x80)
    GameSettings.gBattleTextBuff1 = Memory.readdword(startAddr + 0x84)
    GameSettings.gBattleTypeFlags = Memory.readdword(startAddr + 0x88)
    GameSettings.gBattleWeather = Memory.readdword(startAddr + 0x8C)
    GameSettings.gBattlerAttacker = Memory.readdword(startAddr + 0x90)
    GameSettings.gBattlerPartyIndexes = Memory.readdword(startAddr + 0x94)
    GameSettings.gBattlerTarget = Memory.readdword(startAddr + 0x98)
    GameSettings.gBattlersCount = Memory.readdword(startAddr + 0x9C)
    GameSettings.gBattlescriptCurrInstr = Memory.readdword(startAddr + 0xA0)
    GameSettings.battleHistoryAddr = Memory.readdword(startAddr + 0xA4)
    GameSettings.gProtectStructs = Memory.readdword(startAddr + 0xA8)
    GameSettings.gCurrentTurnActionNumber = Memory.readdword(startAddr + 0xAC)
    GameSettings.gHitMarker = Memory.readdword(startAddr + 0xB0)
    GameSettings.gDisableStructs = Memory.readdword(startAddr + 0xB4)
    GameSettings.gExperienceTables = Memory.readdword(startAddr + 0xB8)
    GameSettings.gLevelUpLearnsets = Memory.readdword(startAddr + 0xBC)
    GameSettings.gLockedMoves = Memory.readdword(startAddr + 0xC0)
    GameSettings.mapGroupsAddr = Memory.readdword(startAddr + 0xC4)
    GameSettings.gMoveToLearn = Memory.readdword(startAddr + 0xC8)
    GameSettings.gMultiUsePlayerCursor = Memory.readdword(startAddr + 0xCC)
    GameSettings.gWildMonHeaders = Memory.readdword(startAddr + 0xD0)
    GameSettings.gBattleStruct = Memory.readdword(startAddr + 0xD4)
    GameSettings.sInGameTrades = Memory.readdword(startAddr + 0xD8)
    GameSettings.sTextSpeedFrameDelays = Memory.readdword(startAddr + 0xDC)
    GameSettings.gNewGamePCItems = Memory.readdword(startAddr + 0xE0)
    GameSettings.sPickupItems = Memory.readdword(startAddr + 0xE4)
    GameSettings.gTutorMoves = Memory.readdword(startAddr + 0xE8)
    GameSettings.sGFRomHeader = Memory.readdword(startAddr + 0xEC)
    GameSettings.sStartMenuWindowId = Memory.readdword(startAddr + 0xF0)
    GameSettings.FriendshipRequiredToEvo = Memory.readdword(startAddr + 0xF4)
    GameSettings.gActionsByTurnOrder = Memory.readdword(startAddr + 0xF8)
    GameSettings.gBaseStats = Memory.readdword(startAddr + 0xFC)
    GameSettings.gBattleCommunication = Memory.readdword(startAddr + 0x100)
    GameSettings.gBattleControllerExecFlags = Memory.readdword(startAddr + 0x104)
    GameSettings.gBattleMainFunc = Memory.readdword(startAddr + 0x108)
    GameSettings.gBattleMons = Memory.readdword(startAddr + 0x10C)
    GameSettings.gPaydayMoney = Memory.readdword(startAddr + 0x110)
    GameSettings.gPlayerPartyCount = Memory.readdword(startAddr + 0x114)
    GameSettings.gSaveBlock1ptr = Memory.readdword(startAddr + 0x118)
    GameSettings.gSaveBlock2ptr = Memory.readdword(startAddr + 0x11C)
    GameSettings.gSideStatuses = Memory.readdword(startAddr + 0x120)
    GameSettings.gSideTimers = Memory.readdword(startAddr + 0x124)
    GameSettings.gSpecialVars = Memory.readdword(startAddr + 0x128)
    GameSettings.gSpecialVar_ItemId = Memory.readdword(startAddr + 0x12C)
    GameSettings.gSpecialVar_Result = Memory.readdword(startAddr + 0x130)
    GameSettings.gTasks = Memory.readdword(startAddr + 0x134)
    GameSettings.gIntroSpecies = Memory.readdword(startAddr + 0x138)
    GameSettings.gTutorialSpecies = Memory.readdword(startAddr + 0x13C)
    GameSettings.BattleScript_FocusPunchSetUp = Memory.readdword(startAddr + 0x188)
    GameSettings.BattleScript_LearnMoveReturn = Memory.readdword(startAddr + 0x18C)
    GameSettings.BattleScript_MoveUsedIsConfused = Memory.readdword(startAddr + 0x190)
    GameSettings.BattleScript_MoveUsedIsConfusedNoMore = Memory.readdword(startAddr + 0x194)
    GameSettings.BattleScript_MoveUsedIsFrozen = Memory.readdword(startAddr + 0x198)
    GameSettings.BattleScript_MoveUsedIsInLove = Memory.readdword(startAddr + 0x19C)
    GameSettings.BattleScript_MoveUsedUnfroze = Memory.readdword(startAddr + 0x1A0)
    GameSettings.BattleScript_MoveUsedWokeUp = Memory.readdword(startAddr + 0x1A4)
    GameSettings.BattleScript_RanAwayUsingMonAbility = Memory.readdword(startAddr + 0x1A8)
    GameSettings.BattleScript_SnatchedMove = Memory.readdword(startAddr + 0x1AC)
    GameSettings.BattleIntroDrawPartySummaryScreens = Memory.readdword(startAddr + 0x1B0)
    GameSettings.BattleIntroOpponentSendsOutMonAnimation = Memory.readdword(startAddr + 0x1B4)
    GameSettings.BattleScript_LearnMoveLoop = Memory.readdword(startAddr + 0x1B8)
    GameSettings.HandleTurnActionSelectionState = Memory.readdword(startAddr + 0x1BC)
    GameSettings.ReturnFromBattleToOverworld = Memory.readdword(startAddr + 0x1C0)
    GameSettings.Task_EvolutionScene = Memory.readdword(startAddr + 0x1C4)
    GameSettings.gWishFutureKnock = Memory.readdword(startAddr + 0x1C8)
    GameSettings.gTrainerBattleOpponent_A = Memory.readdword(startAddr + 0x1CC)
    GameSettings.sBattlerAbilities = Memory.readdword(startAddr + 0x1D0)
    GameSettings.sEvoStruct = Memory.readdword(startAddr + 0x1D4)
    GameSettings.sSpecialFlags = Memory.readdword(startAddr + 0x1D8)
    GameSettings.gBattleMoves = Memory.readdword(startAddr + 0x1DC)
    GameSettings.gBattleScriptingBattler = Memory.readdword(startAddr + 0x1E0)
    GameSettings.moveEndAddr = Memory.readdword(startAddr + 0x1E4)
    GameSettings.gMoveResultFlags = Memory.readdword(startAddr + 0x1E8)
    GameSettings.sBattleBuffersTransferData = Memory.readdword(startAddr + 0x1EC)
    GameSettings.sMonSummaryScreen = Memory.readdword(startAddr + 0x1F0)
    GameSettings.sStartMenuWindowId = Memory.readdword(startAddr + 0x1F4)
    GameSettings.staticEncountersAddr = Memory.readdword(startAddr + 0x1F8)
    GameSettings.gymLeaderTMsAddr = Memory.readdword(startAddr + 0x1FC)
    GameSettings.fieldMoveTutorMovesAddr = Memory.readdword(startAddr + 0x200)
    GameSettings.freeSpaceAddr = Memory.readdword(startAddr + 0x204)
    GameSettings.eliteFourTrainersAddr = Memory.readdword(startAddr + 0x208)
    GameSettings.doublesClassesAddr = Memory.readdword(startAddr + 0x20C)
    GameSettings.regionMapAddr = Memory.readdword(startAddr + 0x210)
    GameSettings.gMapHeader = Memory.readdword(startAddr + 0x214)
    GameSettings.gMainAddr = Memory.readdword(startAddr + 0x218)
    GameSettings.initBattleAddr = Memory.readdword(startAddr + 0x21C)
    GameSettings.returnToFieldAddr = Memory.readdword(startAddr + 0x220)
    GameSettings.doChangeMapAddr = Memory.readdword(startAddr + 0x224)
    GameSettings.overworldAddr = Memory.readdword(startAddr + 0x228)
    GameSettings.initMainMenuAddr = Memory.readdword(startAddr + 0x22C)
    GameSettings.afterEvolutionAddr = Memory.readdword(startAddr + 0x230)
    GameSettings.effectHitAddr = Memory.readdword(startAddr + 0x234)
    GameSettings.fieldCallbackAddr = Memory.readdword(startAddr + 0x238)
    GameSettings.randomizingScreenAddr = Memory.readdword(startAddr + 0x23C)
    GameSettings.sSaveDialogDelay = Memory.readdword(startAddr + 0x240)
    GameSettings.gSaveBlock3ptr = Memory.readdword(startAddr + 0x244)
    GameSettings.roguemonTrackerDataAddr = Memory.readdword(startAddr + 0x248)
    GameSettings.gSpeciesInfoSize = Memory.readdword(startAddr + 0x26C)
    GameSettings.gAbilitiesInfoSize = Memory.readdword(startAddr + 0x270)
    GameSettings.gMovesInfoSize = Memory.readdword(startAddr + 0x274)
    GameSettings.gTrainersSize = Memory.readdword(startAddr + 0x278)
    GameSettings.gTrainerClassesSize = Memory.readdword(startAddr + 0x27C)
    GameSettings.gInGameTradesSize = Memory.readdword(startAddr + 0x280)
    GameSettings.gItemsInfoSize = Memory.readdword(startAddr + 0x284)
    GameSettings.gPickupItemsSize = Memory.readdword(startAddr + 0x288)
    GameSettings.saveblock1TableSize = Memory.readdword(startAddr + 0x28C)
    GameSettings.saveblock2TableSize = Memory.readdword(startAddr + 0x290)
    GameSettings.sizeofBaseStatsPokemon = Memory.readword(startAddr + 0x2B4)
    GameSettings.sizeofPokemon = Memory.readword(startAddr + 0x2B6)
    GameSettings.sizeofBattlePokemon = Memory.readword(startAddr + 0x2B8)
    GameSettings.abilityEntrySize = Memory.readword(startAddr + 0x2BA)
    GameSettings.sizeofAbility = Memory.readword(startAddr + 0x2BC)
    GameSettings.gMoveEntrySize = Memory.readword(startAddr + 0x2BE)
    GameSettings.sizeofBattleMove = Memory.readword(startAddr + 0x2BE)
    GameSettings.sizeofTrainer = Memory.readword(startAddr + 0x2C0)
    GameSettings.sizeofTrainerMon = Memory.readword(startAddr + 0x2C2)
    GameSettings.sizeofTrainerClass = Memory.readword(startAddr + 0x2C4)
    GameSettings.sizeofItem = Memory.readword(startAddr + 0x2C6)
    GameSettings.sizeofTMHMItem = Memory.readword(startAddr + 0x2C8)
    GameSettings.sizeofPokemonSubstruct = Memory.readword(startAddr + 0x2CA)
    GameSettings.sizeofPickupItem = Memory.readword(startAddr + 0x2CC)
    GameSettings.sizeofTaskStruct = Memory.readword(startAddr + 0x2CE)
    GameSettings.bagItemsPocketSize = Memory.readword(startAddr + 0x2D0)
    GameSettings.bagKeyItemsPocketSize = Memory.readword(startAddr + 0x2D2)
    GameSettings.bagBallsPocketSize = Memory.readword(startAddr + 0x2D4)
    GameSettings.bagRoguemonPocketSize = Memory.readword(startAddr + 0x2D6)
    GameSettings.bagTmHmPocketSize = Memory.readword(startAddr + 0x2D8)
    GameSettings.bagBerriesPocketSize = Memory.readword(startAddr + 0x2DA)
    GameSettings.regionMapEntrySize = Memory.readword(startAddr + 0x2DC)
    GameSettings.sizeofProtectStruct = Memory.readword(startAddr + 0x2DE)
    GameSettings.disableStructEntrySize = Memory.readword(startAddr + 0x2E0)
    GameSettings.sizeofExpTablePokemon = Memory.readword(startAddr + 0x2E2)
    GameSettings.sizeofGameStat = Memory.readword(startAddr + 0x2E4)
    GameSettings.sizeofLastMoveStruct = Memory.readword(startAddr + 0x2E6)
    GameSettings.sizeofTrainerItem = Memory.readword(startAddr + 0x2E8)
    GameSettings.sizeofTrainerMonCustomMove = Memory.readword(startAddr + 0x2EA)
    GameSettings.sizeofExpYield = Memory.readword(startAddr + 0x2EC)
    GameSettings.lastEnemyMoveSize = Memory.readword(startAddr + 0x2EE)
    GameSettings.sizeofLastAttackerMove = Memory.readword(startAddr + 0x2F0)
    GameSettings.moveHistoryEntrySize = Memory.readword(startAddr + 0x2F2)
    GameSettings.prizeStateSize = Memory.readword(startAddr + 0x2F4)
    GameSettings.gNumSpecies = Memory.readword(startAddr + 0x316)
    GameSettings.gNumPokemon = Memory.readword(startAddr + 0x318)
    GameSettings.abilitiesCount = Memory.readword(startAddr + 0x31A)
    GameSettings.gNumMoves = Memory.readword(startAddr + 0x31C)
    GameSettings.trainersCount = Memory.readword(startAddr + 0x31E)
    GameSettings.trainerClassCount = Memory.readword(startAddr + 0x320)
    GameSettings.difficultyCount = Memory.readword(startAddr + 0x322)
    GameSettings.ingameTradesCount = Memory.readword(startAddr + 0x324)
    GameSettings.itemsCount = Memory.readword(startAddr + 0x326)
    GameSettings.tmCount = Memory.readword(startAddr + 0x328)
    GameSettings.hmCount = Memory.readword(startAddr + 0x32A)
    GameSettings.gymLeaderTMsCount = Memory.readword(startAddr + 0x32C)
    GameSettings.fieldMoveTutorMovesCount = Memory.readword(startAddr + 0x32E)
    GameSettings.pickupItemsCount = Memory.readword(startAddr + 0x330)
    GameSettings.eliteFourTrainersCount = Memory.readword(startAddr + 0x332)
    GameSettings.doublesClassesCount = Memory.readword(startAddr + 0x334)
    GameSettings.regionMapCount = Memory.readword(startAddr + 0x336)
    GameSettings.bagPocket_Items_Size = Memory.readword(startAddr + 0x338)
    GameSettings.bagPocket_KeyItems_Size = Memory.readword(startAddr + 0x33A)
    GameSettings.bagPocket_Balls_Size = Memory.readword(startAddr + 0x33C)
    GameSettings.bagRoguemonCount = Memory.readword(startAddr + 0x33E)
    GameSettings.bagPocket_TmHm_Size = Memory.readword(startAddr + 0x340)
    GameSettings.bagPocket_Berries_Size = Memory.readword(startAddr + 0x342)
    GameSettings.pokemonNameLength = Memory.readword(startAddr + 0x364)
    GameSettings.sizeofPokemonNickname = Memory.readword(startAddr + 0x366)
    GameSettings.abilityNameLength = Memory.readword(startAddr + 0x368)
    GameSettings.moveNameLength = Memory.readword(startAddr + 0x36A)
    GameSettings.trainerNameLength = Memory.readword(startAddr + 0x36C)
    GameSettings.trainerClassNameLength = Memory.readword(startAddr + 0x36E)
    GameSettings.itemNameLength = Memory.readword(startAddr + 0x370)
    GameSettings.typeNameLength = Memory.readword(startAddr + 0x372)
    GameSettings.playerNameLength = Memory.readword(startAddr + 0x374)
    GameSettings.offsetAbilityName = Memory.readword(startAddr + 0x396)
    GameSettings.offsetAbilityDesc = Memory.readword(startAddr + 0x398)
    GameSettings.offsetSpeciesName = Memory.readword(startAddr + 0x39A)
    GameSettings.offsetSpeciesNatDex = Memory.readword(startAddr + 0x39C)
    GameSettings.offsetSpeciesLearnset = Memory.readword(startAddr + 0x39E)
    GameSettings.offsetSpeciesTeachable = Memory.readword(startAddr + 0x3A0)
    GameSettings.offsetSpeciesEggMoves = Memory.readword(startAddr + 0x3A2)
    GameSettings.offsetSpeciesEvolutions = Memory.readword(startAddr + 0x3A4)
    GameSettings.speciesFormFlagsOffset = Memory.readword(startAddr + 0x3A6)
    GameSettings.offsetItemName = Memory.readword(startAddr + 0x3A8)
    GameSettings.itemDescOffset = Memory.readword(startAddr + 0x3AA)
    GameSettings.offsetItemIcon = Memory.readword(startAddr + 0x3AC)
    GameSettings.offsetItemHoldEffect = Memory.readword(startAddr + 0x3AE)
    GameSettings.offsetItemHoldParam = Memory.readword(startAddr + 0x3B0)
    GameSettings.offsetItemPocket = Memory.readword(startAddr + 0x3B2)
    GameSettings.offsetItemFlags = Memory.readword(startAddr + 0x3B4)
    GameSettings.itemSortTypeOffset = Memory.readword(startAddr + 0x3B6)
    GameSettings.offsetItemPalette = Memory.readword(startAddr + 0x3B8)
    GameSettings.gameRegItemOffset = Memory.readword(startAddr + 0x3BA)
    GameSettings.gameStatsOffset = Memory.readword(startAddr + 0x3BC)
    GameSettings.gameVarsOffset = Memory.readword(startAddr + 0x3BE)
    GameSettings.gameFlagsOffset = Memory.readword(startAddr + 0x3C0)
    GameSettings.offsetBag = Memory.readword(startAddr + 0x3C2)
    GameSettings.bagPocket_Items_offset = Memory.readword(startAddr + 0x3C4)
    GameSettings.bagPocket_KeyItems_offset = Memory.readword(startAddr + 0x3C6)
    GameSettings.bagPocket_Balls_offset = Memory.readword(startAddr + 0x3C8)
    GameSettings.bagRoguemonOffset = Memory.readword(startAddr + 0x3CA)
    GameSettings.bagPocket_TmHm_offset = Memory.readword(startAddr + 0x3CC)
    GameSettings.bagPocket_Berries_offset = Memory.readword(startAddr + 0x3CE)
    GameSettings.offsetTrainerFlagStart = Memory.readword(startAddr + 0x3D0)
    GameSettings.offsetBattleResultsPlayerMoveId = Memory.readword(startAddr + 0x3D2)
    GameSettings.offsetBattleResultsEnemyMoveId = Memory.readword(startAddr + 0x3D4)
    GameSettings.offsetBattleResultsCurrentTurn = Memory.readword(startAddr + 0x3D6)
    GameSettings.offsetBattleResultsEnemyLastMove = Memory.readword(startAddr + 0x3D8)
    GameSettings.offsetBattleResultsPlayerLastMove = Memory.readword(startAddr + 0x3DA)
    GameSettings.offsetBattleResultsLastAttackerMove = Memory.readword(startAddr + 0x3DA)
    GameSettings.gBattleStructLastDamageTaken = Memory.readword(startAddr + 0x3DC)
    GameSettings.gTakenDmg = Memory.readword(startAddr + 0x3DC)
    GameSettings.gBattleStructMoveResultFlags = Memory.readword(startAddr + 0x3DE)
    GameSettings.gBattleStructDistortedSeed = Memory.readword(startAddr + 0x3E0)
    GameSettings.offsetMoveName = Memory.readword(startAddr + 0x3E2)
    GameSettings.offsetMoveDescription = Memory.readword(startAddr + 0x3E4)
    GameSettings.offsetMoveEffects = Memory.readword(startAddr + 0x3E6)
    GameSettings.moveInfoTypeCatPowerOffset = Memory.readword(startAddr + 0x3E8)
    GameSettings.moveInfoAccuracyTargetOffset = Memory.readword(startAddr + 0x3EA)
    GameSettings.moveInfoPpOffset = Memory.readword(startAddr + 0x3EC)
    GameSettings.offsetBattleMoveFlags = Memory.readword(startAddr + 0x3EE)
    GameSettings.moveInfoPriorityOffset = Memory.readword(startAddr + 0x3F0)
    GameSettings.offsetTrainerClass = Memory.readword(startAddr + 0x3F2)
    GameSettings.offsetTrainerGender = Memory.readword(startAddr + 0x3F4)
    GameSettings.offsetTrainerPic = Memory.readword(startAddr + 0x3F6)
    GameSettings.offsetTrainerName = Memory.readword(startAddr + 0x3F8)
    GameSettings.offsetTrainerItems = Memory.readword(startAddr + 0x3FA)
    GameSettings.offsetTrainerDoubleBattle = Memory.readword(startAddr + 0x3FC)
    GameSettings.offsetTrainerFlagsAI = Memory.readword(startAddr + 0x3FE)
    GameSettings.offsetTrainerPartySize = Memory.readword(startAddr + 0x400)
    GameSettings.offsetTrainerPartyPtr = Memory.readword(startAddr + 0x402)
    GameSettings.offsetTrainerMonLevel = Memory.readword(startAddr + 0x404)
    GameSettings.offsetTrainerMonSpecies = Memory.readword(startAddr + 0x406)
    GameSettings.offsetTrainerMonItem = Memory.readword(startAddr + 0x408)
    GameSettings.offsetTrainerMonNoItemMove1 = Memory.readword(startAddr + 0x40A)
    GameSettings.offsetPokemonSubstruct = Memory.readword(startAddr + 0x40C)
    GameSettings.offsetPokemonStatus = Memory.readword(startAddr + 0x40E)
    GameSettings.offsetPokemonStatsLvCurHp = Memory.readword(startAddr + 0x410)
    GameSettings.pokemonCurHPOffset = Memory.readword(startAddr + 0x412)
    GameSettings.offsetPokemonStatsMaxHpAtk = Memory.readword(startAddr + 0x414)
    GameSettings.pokemonAtkStatOffset = Memory.readword(startAddr + 0x416)
    GameSettings.offsetPokemonStatsDefSpe = Memory.readword(startAddr + 0x418)
    GameSettings.pokemonSpeedStatOffset = Memory.readword(startAddr + 0x41A)
    GameSettings.offsetPokemonStatsSpaSpd = Memory.readword(startAddr + 0x41C)
    GameSettings.pokemonSpDefStatOffset = Memory.readword(startAddr + 0x41E)
    GameSettings.offsetBattlePokemonTypes = Memory.readword(startAddr + 0x420)
    GameSettings.offsetDoublesPartner = Memory.readword(startAddr + 0x422)
    GameSettings.offsetBattlePokemonDoublesPartner = Memory.readword(startAddr + 0x422)
    GameSettings.offsetBaseStats = Memory.readword(startAddr + 0x424)
    GameSettings.offsetTypes = Memory.readword(startAddr + 0x426)
    GameSettings.offsetCatchRate = Memory.readword(startAddr + 0x428)
    GameSettings.offsetExpYield = Memory.readword(startAddr + 0x42A)
    GameSettings.offsetBaseFriendship = Memory.readword(startAddr + 0x42C)
    GameSettings.offsetAbilities = Memory.readword(startAddr + 0x42E)
    GameSettings.offsetGenderRatio = Memory.readword(startAddr + 0x430)
    GameSettings.offsetGrowthRate = Memory.readword(startAddr + 0x432)
    GameSettings.pokemonWeightOffset = Memory.readword(startAddr + 0x434)
    GameSettings.offsetBattlePokemonStatStages = Memory.readword(startAddr + 0x436)
    GameSettings.pokemonBattleTypesOffset = Memory.readword(startAddr + 0x438)
    GameSettings.pokemonBattleHpOffset = Memory.readword(startAddr + 0x43A)
    GameSettings.offsetMapHeaderLayoutId = Memory.readword(startAddr + 0x43C)
    GameSettings.regionMapNameOffset = Memory.readword(startAddr + 0x43E)
    GameSettings.offsetEvoInfoTaskId = Memory.readword(startAddr + 0x440)
    GameSettings.offsetTaskIsActive = Memory.readword(startAddr + 0x442)
    GameSettings.disabledMoveOffset = Memory.readword(startAddr + 0x444)
    GameSettings.encoredMoveOffset = Memory.readword(startAddr + 0x446)
    GameSettings.protectUsesOffset = Memory.readword(startAddr + 0x448)
    GameSettings.substituteHPOffset = Memory.readword(startAddr + 0x44A)
    GameSettings.encoredMovePosOffset = Memory.readword(startAddr + 0x44C)
    GameSettings.disableTimerOffset = Memory.readword(startAddr + 0x44E)
    GameSettings.encoreTimerOffset = Memory.readword(startAddr + 0x450)
    GameSettings.perishSongTimerOffset = Memory.readword(startAddr + 0x452)
    GameSettings.rolloutTimerOffset = Memory.readword(startAddr + 0x454)
    GameSettings.rolloutStartOffset = Memory.readword(startAddr + 0x456)
    GameSettings.tauntTimerOffset = Memory.readword(startAddr + 0x458)
    GameSettings.furyCutterCounterOffset = Memory.readword(startAddr + 0x45A)
    GameSettings.preventEscapeOffset = Memory.readword(startAddr + 0x45C)
    GameSettings.sureHitBattlerOffset = Memory.readword(startAddr + 0x45E)
    GameSettings.isFirstTurnOffset = Memory.readword(startAddr + 0x460)
    GameSettings.mimickedMovesOffset = Memory.readword(startAddr + 0x462)
    GameSettings.rechargeTimerOffset = Memory.readword(startAddr + 0x464)
    GameSettings.autotomizeCountOffset = Memory.readword(startAddr + 0x466)
    GameSettings.slowStartTimerOffset = Memory.readword(startAddr + 0x468)
    GameSettings.embargoTimerOffset = Memory.readword(startAddr + 0x46A)
    GameSettings.offsetRivalName = Memory.readword(startAddr + 0x46C)
    GameSettings.offsetDexSeen = Memory.readword(startAddr + 0x46E)
    GameSettings.offsetDexCaught = Memory.readword(startAddr + 0x470)
    GameSettings.offsetOptionsButtonMode = Memory.readword(startAddr + 0x472)
    GameSettings.offsetPokedex = Memory.readword(startAddr + 0x474)
    GameSettings.offsetPokemonGettingExp = Memory.readword(startAddr + 0x476)
    GameSettings.battleAbilitiesOffset = Memory.readword(startAddr + 0x478)
    GameSettings.battleMovesOffset = Memory.readword(startAddr + 0x47A)
    GameSettings.battleVolatilesOffset = Memory.readword(startAddr + 0x47C)
    GameSettings.offsetStarterMonChoiceFRLG = Memory.readword(startAddr + 0x47E)
    GameSettings.offsetRepelStepCountFRLG = Memory.readword(startAddr + 0x480)
    GameSettings.offsetSysFlagStartFRLG = Memory.readword(startAddr + 0x482)
    GameSettings.offsetSysFlagSafariModeFRLG = Memory.readword(startAddr + 0x484)
    GameSettings.offsetBattleCommConfirmedCount = Memory.readword(startAddr + 0x486)
    GameSettings.offsetBattleCommLevitate = Memory.readword(startAddr + 0x488)
    GameSettings.itemBallPicOffset = Memory.readword(startAddr + 0x48A)
    GameSettings.roguemonAscensionOffset = Memory.readword(startAddr + 0x48C)
    GameSettings.roguemonRunTypeOffset = Memory.readword(startAddr + 0x48E)
    GameSettings.backToTowerOffset = Memory.readword(startAddr + 0x490)
    GameSettings.awaitRandomizationOffset = Memory.readword(startAddr + 0x492)
    GameSettings.segmentPrevOffset = Memory.readword(startAddr + 0x494)
    GameSettings.segmentNextOffset = Memory.readword(startAddr + 0x496)
    GameSettings.badgeOffset = Memory.readword(startAddr + 0x498)
    GameSettings.TMItemStartIndex = Memory.readword(startAddr + 0x49A)
    GameSettings.regionMapStartIndex = Memory.readword(startAddr + 0x49C)
    GameSettings.roguemonTrackerActionOffset = Memory.readword(startAddr + 0x49E)
    GameSettings.roguemonTrackerActionCounterOffset = Memory.readword(startAddr + 0x4A0)
    GameSettings.roguemonTrackerActionArgOffset = Memory.readword(startAddr + 0x4A2)
    GameSettings.roguemonTrackerCleansingPhaseOffset = Memory.readword(startAddr + 0x4A4)
    GameSettings.roguemonTrackerEvolutionPendingOffset = Memory.readword(startAddr + 0x4A6)
    GameSettings.roguemonTrackerCmdHeadOffset = Memory.readword(startAddr + 0x4A8)
    GameSettings.roguemonTrackerCmdTailOffset = Memory.readword(startAddr + 0x4AA)
    GameSettings.roguemonTrackerCmdCountOffset = Memory.readword(startAddr + 0x4AC)
    GameSettings.roguemonTrackerCmdIdsOffset = Memory.readword(startAddr + 0x4AE)
    GameSettings.roguemonTrackerCmdArg0Offset = Memory.readword(startAddr + 0x4B0)
    GameSettings.roguemonTrackerCmdArg1Offset = Memory.readword(startAddr + 0x4B2)
    GameSettings.roguemonTrackerCmdArg2Offset = Memory.readword(startAddr + 0x4B4)
    GameSettings.roguemonTrackerCmdResultOffset = Memory.readword(startAddr + 0x4B6)
    GameSettings.roguemonTrackerCmdResultCounterOffset = Memory.readword(startAddr + 0x4B8)
    GameSettings.roguemonTrackerCmdResultArgOffset = Memory.readword(startAddr + 0x4BA)
    GameSettings.roguemonTrackerCmdQueueMax = Memory.readword(startAddr + 0x4BC)
    GameSettings.roguemonTrackerDataSize = Memory.readword(startAddr + 0x4BE)
    GameSettings.segmentStateOffset = Memory.readword(startAddr + 0x4C0)
    GameSettings.segmentStateCurrentIdOffset = Memory.readword(startAddr + 0x4C2)
    GameSettings.segmentStateCurrentIndexOffset = Memory.readword(startAddr + 0x4C4)
    GameSettings.segmentStateSegmentCountOffset = Memory.readword(startAddr + 0x4C6)
    GameSettings.segmentStateFlagsOffset = Memory.readword(startAddr + 0x4C8)
    GameSettings.segmentStateCompletedMaskOffset = Memory.readword(startAddr + 0x4CA)
    GameSettings.segmentStateOptionalCountOffset = Memory.readword(startAddr + 0x4CC)
    GameSettings.segmentStateOptionalQueueOffset = Memory.readword(startAddr + 0x4CE)
    GameSettings.segmentStateChangeCounterOffset = Memory.readword(startAddr + 0x4D0)
    GameSettings.segmentStateHpCapModifierOffset = Memory.readword(startAddr + 0x4D2)
    GameSettings.segmentStateStatusCapModifierOffset = Memory.readword(startAddr + 0x4D4)
    GameSettings.segmentStatePocketSandUsedOffset = Memory.readword(startAddr + 0x4D6)
    GameSettings.segmentDefHpCapDeltaOffset = Memory.readword(startAddr + 0x4D8)
    GameSettings.segmentDefStatusCapDeltaOffset = Memory.readword(startAddr + 0x4DA)
    GameSettings.segmentDefNameOffset = Memory.readword(startAddr + 0x4DC)
    GameSettings.segmentDefsAddr = Memory.readdword(startAddr + 0x4E0)
    GameSettings.segmentDefEntrySize = Memory.readword(startAddr + 0x4E4)
    GameSettings.segmentDefsCount = Memory.readword(startAddr + 0x4E6)
    GameSettings.prizeStateOffset = Memory.readword(startAddr + 0x4E8)
    GameSettings.prizeStateSegmentIdOffset = Memory.readword(startAddr + 0x4EA)
    GameSettings.prizeStateOptionsCountOffset = Memory.readword(startAddr + 0x4EC)
    GameSettings.prizeStateFlagsOffset = Memory.readword(startAddr + 0x4EE)
    GameSettings.prizeStateCurrentItemsOffset = Memory.readword(startAddr + 0x4F0)
    GameSettings.prizeStateBaseSeedOffset = Memory.readword(startAddr + 0x4F2)
    GameSettings.prizeStatePoolSeedOffset = Memory.readword(startAddr + 0x4F4)
    GameSettings.prizeStatePoolCursorOffset = Memory.readword(startAddr + 0x4F6)
    GameSettings.prizeStatePoolSizeOffset = Memory.readword(startAddr + 0x4F8)
    GameSettings.prizeStateQueueHeadOffset = Memory.readword(startAddr + 0x4FA)
    GameSettings.prizeStateQueueTailOffset = Memory.readword(startAddr + 0x4FC)
    GameSettings.prizeStateQueueCountOffset = Memory.readword(startAddr + 0x4FE)
    GameSettings.prizeStateQueueTasksOffset = Memory.readword(startAddr + 0x500)
    GameSettings.prizeStateQueueArg0Offset = Memory.readword(startAddr + 0x502)
    GameSettings.prizeStateQueueArg1Offset = Memory.readword(startAddr + 0x504)
    GameSettings.prizeStatePendingTaskIdOffset = Memory.readword(startAddr + 0x506)
    GameSettings.prizeStatePendingTaskValueU8Offset = Memory.readword(startAddr + 0x508)
    GameSettings.prizeStatePendingTaskValueU16Offset = Memory.readword(startAddr + 0x50A)
    GameSettings.prizeStateLastSelectedOffset = Memory.readword(startAddr + 0x50C)
    GameSettings.prizeStateArmorPlatingModeOffset = Memory.readword(startAddr + 0x50E)
    GameSettings.prizeStateBoosterShotModeOffset = Memory.readword(startAddr + 0x510)
    GameSettings.prizeStateBoosterShotMoveIdOffset = Memory.readword(startAddr + 0x512)
    GameSettings.prizeStateTeraOrbTypeOffset = Memory.readword(startAddr + 0x514)
    GameSettings.prizeStateHyperTrainingStatOffset = Memory.readword(startAddr + 0x516)
    GameSettings.prizeStatePotionInvestmentLastSegmentOffset = Memory.readword(startAddr + 0x518)
    GameSettings.prizeStatePotionInvestmentValueOffset = Memory.readword(startAddr + 0x51A)
    GameSettings.prizeStatePotionInvestmentOfferItemOffset = Memory.readword(startAddr + 0x51C)
    GameSettings.prizeStateNatureMintBoostOffset = Memory.readword(startAddr + 0x51E)
    GameSettings.prizeStateNatureMintNerfOffset = Memory.readword(startAddr + 0x520)
    GameSettings.prizeStateRoguestoneOfferIndexOffset = Memory.readword(startAddr + 0x522)
    GameSettings.prizeStateRoguestoneOfferHpCostOffset = Memory.readword(startAddr + 0x524)
    GameSettings.prizeStateStarterPackMoveOffset = Memory.readword(startAddr + 0x526)
    GameSettings.prizeStateStarterPackOptionOffset = Memory.readword(startAddr + 0x528)
    GameSettings.prizeStateChangeCounterOffset = Memory.readword(startAddr + 0x52A)
    GameSettings.prizeHistoryOffset = Memory.readword(startAddr + 0x52C)
    GameSettings.prizeHistoryEntrySize = Memory.readword(startAddr + 0x52E)
    GameSettings.prizeHistoryCount = Memory.readword(startAddr + 0x530)
    GameSettings.prizeHistorySegmentIdOffset = Memory.readword(startAddr + 0x532)
    GameSettings.prizeHistoryOptionsCountOffset = Memory.readword(startAddr + 0x534)
    GameSettings.prizeHistorySelectedIndexOffset = Memory.readword(startAddr + 0x536)
    GameSettings.prizeHistoryExtraKindOffset = Memory.readword(startAddr + 0x538)
    GameSettings.prizeHistoryOptionIdsOffset = Memory.readword(startAddr + 0x53A)
    GameSettings.prizeHistoryExtraValueOffset = Memory.readword(startAddr + 0x53C)
    GameSettings.prizeHistoryExtraValue2Offset = Memory.readword(startAddr + 0x53E)
    GameSettings.curseStateOffset = Memory.readword(startAddr + 0x540)
    GameSettings.curseStateVersionOffset = Memory.readword(startAddr + 0x542)
    GameSettings.curseStateAssignedCountOffset = Memory.readword(startAddr + 0x544)
    GameSettings.curseStateWardedSegmentOffset = Memory.readword(startAddr + 0x546)
    GameSettings.curseStateClairvoyanceUsedOffset = Memory.readword(startAddr + 0x548)
    GameSettings.curseStateBaseSeedOffset = Memory.readword(startAddr + 0x54A)
    GameSettings.curseStateStateFlagsOffset = Memory.readword(startAddr + 0x54C)
    GameSettings.curseStateActiveCurseIdOffset = Memory.readword(startAddr + 0x54E)
    GameSettings.curseStateAssignedCursesOffset = Memory.readword(startAddr + 0x550)
    GameSettings.curseStateAssignedSegmentsOffset = Memory.readword(startAddr + 0x552)
    GameSettings.curseStateSwapIndexAOffset = Memory.readword(startAddr + 0x554)
    GameSettings.curseStateSwapIndexBOffset = Memory.readword(startAddr + 0x556)
    GameSettings.curseStateTimeWarpExpOffset = Memory.readword(startAddr + 0x558)
    GameSettings.curseStateChangeCounterOffset = Memory.readword(startAddr + 0x55A)
    GameSettings.curseStateSize = Memory.readword(startAddr + 0x55C)
    GameSettings.curseAssignmentMax = Memory.readword(startAddr + 0x55E)
    GameSettings.curseIdCount = Memory.readword(startAddr + 0x560)
    GameSettings.curseDefsAddr = Memory.readdword(startAddr + 0x564)
    GameSettings.curseDefEntrySize = Memory.readword(startAddr + 0x568)
    GameSettings.curseDefIdOffset = Memory.readword(startAddr + 0x56A)
    GameSettings.curseDefFlagsOffset = Memory.readword(startAddr + 0x56C)
    GameSettings.curseDefNameOffset = Memory.readword(startAddr + 0x56E)
    GameSettings.curseDefDescriptionOffset = Memory.readword(startAddr + 0x570)
    GameSettings.roguemonItemUnlockFlagsOffset = Memory.readword(startAddr + 0x572)
    GameSettings.roguemonTempItemUnlockFlagsOffset = Memory.readword(startAddr + 0x574)
    GameSettings.roguemonTmUseUnlockFlagsOffset = Memory.readword(startAddr + 0x576)
    GameSettings.roguemonItemUnlockFlagsSize = Memory.readword(startAddr + 0x578)
    GameSettings.roguemonTmUseUnlockFlagsSize = Memory.readword(startAddr + 0x57A)
    GameSettings.prizeDefKindOffset = Memory.readword(startAddr + 0x57C)
    GameSettings.prizeDefChoiceCountOffset = Memory.readword(startAddr + 0x57E)
    GameSettings.prizeDefGrantsOffset = Memory.readword(startAddr + 0x580)
    GameSettings.prizeDefChoicesOffset = Memory.readword(startAddr + 0x582)
    GameSettings.prizeDefNameOffset = Memory.readword(startAddr + 0x584)
    GameSettings.prizeDefDescriptionOffset = Memory.readword(startAddr + 0x586)
    GameSettings.prizeDefImageOffset = Memory.readword(startAddr + 0x588)
    GameSettings.prizeDefsAddr = Memory.readdword(startAddr + 0x58C)
    GameSettings.prizeDefEntrySize = Memory.readword(startAddr + 0x590)
    GameSettings.prizeDefsCount = Memory.readword(startAddr + 0x592)
    GameSettings.roguemonItemDefItemIdOffset = Memory.readword(startAddr + 0x594)
    GameSettings.roguemonItemDefDisplayTypeOffset = Memory.readword(startAddr + 0x596)
    GameSettings.roguemonItemDefDisplayContextOffset = Memory.readword(startAddr + 0x598)
    GameSettings.roguemonItemDefIconOffset = Memory.readword(startAddr + 0x59A)
    GameSettings.roguemonItemDefsAddr = Memory.readdword(startAddr + 0x59C)
    GameSettings.roguemonItemDefEntrySize = Memory.readword(startAddr + 0x5A0)
    GameSettings.roguemonItemDefsCount = Memory.readword(startAddr + 0x5A2)
    GameSettings.moveEnhancedDescAddr = Memory.readdword(startAddr + 0x5A4)
    GameSettings.moveEnhancedDescCount = Memory.readword(startAddr + 0x5A8)
    GameSettings.itemEnhancedDescAddr = Memory.readdword(startAddr + 0x5AC)
    GameSettings.itemEnhancedDescCount = Memory.readword(startAddr + 0x5B0)
    GameSettings.abilityEnhancedDescAddr = Memory.readdword(startAddr + 0x5B4)
    GameSettings.abilityEnhancedDescCount = Memory.readword(startAddr + 0x5B8)
    GameSettings.tutorMovesTerminator = Memory.readword(startAddr + 0x5CE)
    GameSettings.moveInfoTypeMask = Memory.readword(startAddr + 0x5D0)
    GameSettings.moveInfoCategoryMask = Memory.readword(startAddr + 0x5D2)
    GameSettings.moveInfoPowerMask = Memory.readword(startAddr + 0x5D4)
    GameSettings.moveInfoAccuracyMask = Memory.readword(startAddr + 0x5D6)
    GameSettings.moveInfoTargetMask = Memory.readword(startAddr + 0x5D8)
    GameSettings.hitmarkerFlag = Memory.readdword(startAddr + 0x5DC)
    GameSettings.hitmarkerFlag80000 = Memory.readdword(startAddr + 0x5DC)
    GameSettings.moveResultsFlag = Memory.readword(startAddr + 0x5E0)
    GameSettings.trainerGenderMask = Memory.readword(startAddr + 0x5E2)
    GameSettings.trainerBattleTypeMask = Memory.readword(startAddr + 0x5E4)
    GameSettings.pokemonAbilityNumIndex = Memory.readword(startAddr + 0x5E6)
    GameSettings.pokemonAbilityNumMask = Memory.readword(startAddr + 0x5E8)
    GameSettings.uidStampOffset = Memory.readword(startAddr + 0x5EA)
    GameSettings.ascensionStampOffset = Memory.readword(startAddr + 0x5EC)
    GameSettings.typeStampOffset = Memory.readword(startAddr + 0x5EE)

    -- TM/HM palette pointers
    GameSettings.gItemIconPalette_TMHM = {}
    do
        local base = startAddr + 0x140
        for i = 0, 17 do
            GameSettings.gItemIconPalette_TMHM[i + 1] = Memory.readdword(base + (i * 4))
        end
    end
    return true
end

-- Fail fast on missing GameSettings keys
local warned = {}
setmetatable(GameSettings, {
    __index = function(t, k)
        local msg = string.format("GameSettings.%s is nil", tostring(k))
        if warned[k] == nil then
            warned[k] = true
            Utils.printDebug("[WARN] %s", msg)
        end
        if not warned.__fatal then
            warned.__fatal = true
            local main = rawget(_G, "Main")
            if main and main.DisplayError then
                main.DisplayError(msg .. "\n\nRogueMon GameSettings is missing data. The tracker will now exit.")
            end
            if main and main.ExitSafely then
                main.ExitSafely(true)
            end
        end
        error(msg)
    end
})

-- Critical fields that must be present and non-zero for the tracker to function
local REQUIRED_POINTER_FIELDS = {
    -- Save block pointers (used for state reads/writes)
    "gSaveBlock1ptr",
    "gSaveBlock2ptr",
    "gSaveBlock3ptr",
    -- Main state detection
    "gMainAddr",
    "overworldAddr",
    -- Battle data addresses
    "gBattleMons",
    "gPlayerParty",
    "gEnemyParty",
    "gBattleTypeFlags",
    -- Data table addresses
    "gSpeciesInfo",
    "gBattleMoves",
    "gAbilitiesInfo",
    "gItemsInfo",
    -- RogueMon-specific addresses
    "roguemonTrackerDataAddr",
    "segmentDefsAddr",
    "prizeDefsAddr",
}

local REQUIRED_SIZE_FIELDS = {
    -- Struct sizes (must be > 0)
    "sizeofPokemon",
    "sizeofBattlePokemon",
    "sizeofBattleMove",
    "sizeofBaseStatsPokemon",
    "sizeofItem",
    "sizeofAbility",
    -- Entry counts (must be > 0)
    "gNumSpecies",
    "gNumMoves",
    "abilitiesCount",
    "itemsCount",
    "segmentDefsCount",
    "prizeDefsCount",
}

local REQUIRED_OFFSET_FIELDS = {
    -- RogueMon state offsets
    "segmentStateOffset",
    "prizeStateOffset",
    "prizeHistoryOffset",
    -- Data access offsets
    "offsetSpeciesName",
    "offsetMoveName",
    "offsetAbilityName",
    "offsetItemName",
}

function RoguemonGameSettings.validateRequiredFields()
    local errors = {}

    -- Check pointer fields (must be non-nil and non-zero)
    for _, field in ipairs(REQUIRED_POINTER_FIELDS) do
        local val = rawget(GameSettings, field)
        if val == nil then
            table.insert(errors, string.format("Missing required field: %s", field))
        elseif type(val) ~= "number" then
            table.insert(errors, string.format("Invalid type for %s: expected number, got %s", field, type(val)))
        elseif val == 0 then
            table.insert(errors, string.format("Required pointer %s is zero", field))
        end
    end

    -- Check size/count fields (must be non-nil, number, and > 0)
    for _, field in ipairs(REQUIRED_SIZE_FIELDS) do
        local val = rawget(GameSettings, field)
        if val == nil then
            table.insert(errors, string.format("Missing required field: %s", field))
        elseif type(val) ~= "number" then
            table.insert(errors, string.format("Invalid type for %s: expected number, got %s", field, type(val)))
        elseif val <= 0 then
            table.insert(errors, string.format("Required size/count %s must be > 0, got %d", field, val))
        end
    end

    -- Check offset fields (must be non-nil and number; 0 may be valid)
    for _, field in ipairs(REQUIRED_OFFSET_FIELDS) do
        local val = rawget(GameSettings, field)
        if val == nil then
            table.insert(errors, string.format("Missing required field: %s", field))
        elseif type(val) ~= "number" then
            table.insert(errors, string.format("Invalid type for %s: expected number, got %s", field, type(val)))
        end
    end

    if #errors > 0 then
        local msg = "GameSettings validation failed:\n" .. table.concat(errors, "\n")
        Utils.printDebug("[ERROR] %s", msg)
        return false, msg
    end

    return true
end

return RoguemonGameSettings