-- Auto-generated by generate-segment-locations.py
-- Do not edit manually; regenerate from ROM data.
-- Trainer locations come from TrainerRouteData.lua.
return {
    items = {
        [40] = { layout = 5, x = 8, y = 4, type = 0 }, -- field: FLAG_HIDE_BULBASAUR_BALL
        [41] = { layout = 5, x = 9, y = 4, type = 0 }, -- field: FLAG_HIDE_SQUIRTLE_BALL
        [42] = { layout = 5, x = 10, y = 4, type = 0 }, -- field: FLAG_HIDE_CHARMANDER_BALL
        [43] = { layout = 5, x = 6, y = 3, type = 0 }, -- field: FLAG_HIDE_OAK_IN_HIS_LAB
        [44] = { layout = 61, x = 10, y = 8, type = 0 }, -- field: FLAG_HIDE_OAK_IN_PALLET_TOWN
        [45] = { layout = 5, x = 5, y = 4, type = 0 }, -- field: FLAG_HIDE_RIVAL_IN_LAB
        [46] = { layout = 63, x = 42, y = 20, type = 0 }, -- field: FLAG_HIDE_PEWTER_CITY_GYM_GUIDE
        [47] = { layout = 99, x = 13, y = 7, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_DOME_FOSSIL
        [48] = { layout = 99, x = 14, y = 7, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_HELIX_FOSSIL
        [49] = { layout = 95, x = 12, y = 15, type = 0 }, -- field: FLAG_HIDE_NUGGET_BRIDGE_ROCKET
        [50] = { layout = 152, x = 10, y = 6, type = 0 }, -- field: FLAG_HIDE_BILL_CLEFAIRY
        [51] = { layout = 152, x = 7, y = 5, type = 0 }, -- field: FLAG_HIDE_BILL_HUMAN_SEA_COTTAGE
        [52] = { layout = 150, x = 11, y = 4, type = 0, floor = "7F" }, -- field: FLAG_HIDE_TOWER_FUJI
        [53] = { layout = 256, x = 3, y = 3, type = 0 }, -- field: FLAG_HIDE_POKEHOUSE_FUJI
        [54] = { layout = 114, x = 3, y = 2, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_LIFT_KEY
        [55] = { layout = 114, x = 20, y = 5, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_SILPH_SCOPE
        [56] = { layout = 114, x = 19, y = 4, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_HIDEOUT_GIOVANNI
        [57] = { layout = 3, x = 6, y = 4, type = 0 }, -- field: FLAG_HIDE_TOWN_MAP
        [58] = { layout = 5, x = 5, y = 1, type = 0 }, -- field: FLAG_HIDE_POKEDEX
        [59] = { layout = 64, x = 33, y = 6, type = 0 }, -- field: FLAG_HIDE_CERULEAN_ROCKET
        [60] = { layout = 64, x = 22, y = 0, type = 0 }, -- field: FLAG_HIDE_CERULEAN_RIVAL
        [61] = { layout = 103, x = 30, y = 2, type = 0 }, -- field: FLAG_HIDE_SS_ANNE_RIVAL
        [62] = { layout = 189, x = 48, y = 24, type = 0 }, -- field: FLAG_HIDE_SAFFRON_ROCKETS
        [63] = { layout = 115, x = 3, y = 7, type = 0, floor = "1F" }, -- field: FLAG_HIDE_SAFFRON_CIVILIANS
        [64] = { layout = 139, x = 22, y = 12, type = 0, floor = "1F" }, -- field: FLAG_HIDE_SEAFOAM_1F_BOULDER_1
        [65] = { layout = 139, x = 32, y = 9, type = 0, floor = "1F" }, -- field: FLAG_HIDE_SEAFOAM_1F_BOULDER_2
        [66] = { layout = 140, x = 22, y = 8, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_SEAFOAM_B1F_BOULDER_1
        [67] = { layout = 140, x = 30, y = 8, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_SEAFOAM_B1F_BOULDER_2
        [68] = { layout = 141, x = 22, y = 8, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_SEAFOAM_B2F_BOULDER_1
        [69] = { layout = 141, x = 30, y = 8, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_SEAFOAM_B2F_BOULDER_2
        [70] = { layout = 142, x = 23, y = 8, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_SEAFOAM_B3F_BOULDER_1
        [71] = { layout = 142, x = 24, y = 8, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_SEAFOAM_B3F_BOULDER_2
        [72] = { layout = 142, x = 6, y = 17, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_SEAFOAM_B3F_BOULDER_3
        [73] = { layout = 142, x = 9, y = 16, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_SEAFOAM_B3F_BOULDER_4
        [74] = { layout = 142, x = 12, y = 16, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_SEAFOAM_B3F_BOULDER_5
        [75] = { layout = 142, x = 13, y = 16, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_SEAFOAM_B3F_BOULDER_6
        [76] = { layout = 143, x = 8, y = 18, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_SEAFOAM_B4F_BOULDER_1
        [77] = { layout = 143, x = 9, y = 18, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_SEAFOAM_B4F_BOULDER_2
        [78] = { layout = 121, x = 2, y = 6, type = 0, floor = "7F" }, -- field: FLAG_HIDE_SILPH_RIVAL
        [79] = { layout = 93, x = 25, y = 4, type = 0 }, -- field: FLAG_HIDE_ROUTE_22_RIVAL
        [80] = { layout = 63, x = 33, y = 17, type = 0 }, -- field: FLAG_HIDE_PEWTER_MUSEUM_GUIDE
        [81] = { layout = 145, x = 16, y = 5, type = 0, floor = "2F" }, -- field: FLAG_HIDE_TOWER_RIVAL
        [82] = { layout = 263, x = 9, y = 6, type = 0 }, -- field: FLAG_HIDE_MOLTRES
        [83] = { layout = 123, x = 1, y = 6, type = 0, floor = "9F" }, -- field: FLAG_HIDE_SILPH_ROCKETS
        [84] = { layout = 83, x = 14, y = 70, type = 0 }, -- field: FLAG_HIDE_ROUTE_12_SNORLAX
        [85] = { layout = 34, x = 2, y = 2, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_GIOVANNI
        [86] = { layout = 162, x = 22, y = 3, type = 0, floor = "1F" }, -- field: FLAG_HIDE_OLD_AMBER
        [87] = { layout = 170, x = 7, y = 3, type = 0 }, -- field: FLAG_HIDE_EEVEE_BALL
        [90] = { layout = 199, x = 6, y = 15, type = 0 }, -- field: FLAG_HIDE_OAK_IN_CHAMP_ROOM
        [91] = { layout = 25, x = 11, y = 2, type = 0 }, -- field: FLAG_HIDE_GAME_CORNER_ROCKET
        [92] = { layout = 64, x = 1, y = 13, type = 0 }, -- field: FLAG_HIDE_CERULEAN_CAVE_GUARD
        [93] = { layout = 151, x = 5, y = 11, type = 0 }, -- field: FLAG_HIDE_ZAPDOS
        [94] = { layout = 150, x = 9, y = 10, type = 0, floor = "7F" }, -- field: FLAG_HIDE_TOWER_ROCKET_1
        [95] = { layout = 67, x = 47, y = 24, type = 0 }, -- field: FLAG_HIDE_CELADON_ROCKETS
        [96] = { layout = 210, x = 5, y = 3, type = 0 }, -- field: FLAG_HIDE_DOJO_HITMONLEE_BALL
        [97] = { layout = 210, x = 7, y = 3, type = 0 }, -- field: FLAG_HIDE_DOJO_HITMONCHAN_BALL
        [98] = { layout = 69, x = 20, y = 7, type = 0 }, -- field: FLAG_HIDE_CINNABAR_BILL
        [99] = { layout = 244, x = 4, y = 6, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_1
        [100] = { layout = 244, x = 13, y = 8, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_2
        [101] = { layout = 244, x = 10, y = 6, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_3
        [102] = { layout = 244, x = 1, y = 8, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_4
        [103] = { layout = 244, x = 13, y = 4, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_5
        [104] = { layout = 244, x = 7, y = 4, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_6
        [105] = { layout = 244, x = 1, y = 4, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_7
        [106] = { layout = 244, x = 7, y = 8, type = 0 }, -- field: FLAG_HIDE_UNION_ROOM_PLAYER_8
        [107] = { layout = 69, x = 23, y = 7, type = 0 }, -- field: FLAG_HIDE_CINNABAR_SEAGALLOP
        [108] = { layout = 245, x = 5, y = 11, type = 0 }, -- field: FLAG_HIDE_SAFFRON_FAN_CLUB_BLACKBELT
        [109] = { layout = 245, x = 7, y = 12, type = 0 }, -- field: FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER
        [110] = { layout = 245, x = 9, y = 11, type = 0 }, -- field: FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN
        [111] = { layout = 245, x = 9, y = 12, type = 0 }, -- field: FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY
        [112] = { layout = 9, x = 1, y = 2, type = 0, floor = "2F" }, -- field: FLAG_HIDE_MG_DELIVERYMEN
        [113] = { layout = 212, x = 12, y = 16, type = 0 }, -- field: FLAG_HIDE_ONE_ISLAND_BILL
        [114] = { layout = 253, x = 14, y = 6, type = 0, floor = "1F" }, -- field: FLAG_HIDE_ONE_ISLAND_POKECENTER_BILL
        [115] = { layout = 253, x = 15, y = 6, type = 0, floor = "1F" }, -- field: FLAG_HIDE_ONE_ISLAND_POKECENTER_CELIO
        [116] = { layout = 254, x = 5, y = 8, type = 0 }, -- field: FLAG_HIDE_TWO_ISLAND_GAME_CORNER_BIKER
        [117] = { layout = 254, x = 6, y = 5, type = 0 }, -- field: FLAG_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE
        [118] = { layout = 28, x = 3, y = 4, type = 0 }, -- field: FLAG_HIDE_LOSTELLE_IN_HER_HOME
        [121] = { layout = 223, x = 13, y = 10, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_BIKERS
        [122] = { layout = 252, x = 4, y = 8, type = 0 }, -- field: FLAG_HIDE_LOSTELLE_IN_BERRY_FOREST
        [123] = { layout = 213, x = 31, y = 6, type = 0 }, -- field: FLAG_HIDE_TWO_ISLAND_WOMAN
        [124] = { layout = 213, x = 30, y = 11, type = 0 }, -- field: FLAG_HIDE_TWO_ISLAND_BEAUTY
        [125] = { layout = 213, x = 27, y = 6, type = 0 }, -- field: FLAG_HIDE_TWO_ISLAND_SUPER_NERD
        [126] = { layout = 214, x = 8, y = 23, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_ANTIBIKERS
        [127] = { layout = 63, x = 10, y = 8, type = 0 }, -- field: FLAG_HIDE_PEWTER_RIVAL
        [128] = { layout = 87, x = 31, y = 13, type = 0 }, -- field: FLAG_HIDE_ROUTE_16_SNORLAX
        [129] = { layout = 136, x = 7, y = 12, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_MEWTWO
        [130] = { layout = 143, x = 9, y = 2, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_ARTICUNO
        [131] = { layout = 150, x = 13, y = 8, type = 0, floor = "7F" }, -- field: FLAG_HIDE_TOWER_ROCKET_2
        [132] = { layout = 150, x = 9, y = 6, type = 0, floor = "7F" }, -- field: FLAG_HIDE_TOWER_ROCKET_3
        [133] = { layout = 151, x = 30, y = 38, type = 0 }, -- field: FLAG_HIDE_POWER_PLANT_ELECTRODE_1
        [134] = { layout = 151, x = 36, y = 5, type = 0 }, -- field: FLAG_HIDE_POWER_PLANT_ELECTRODE_2
        [135] = { layout = 101, x = 30, y = 16, type = 0 }, -- field: FLAG_HIDE_SS_ANNE
        [136] = { layout = 232, x = 9, y = 24, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_ROCKETS
        [137] = { layout = 262, x = 42, y = 40, type = 0 }, -- field: FLAG_HIDE_MT_EMBER_EXTERIOR_ROCKETS
        [138] = { layout = 273, x = 7, y = 7, type = 0, floor = "B5F" }, -- field: FLAG_HIDE_RUBY
        [139] = { layout = 278, x = 12, y = 16, type = 0 }, -- field: FLAG_HIDE_ICEFALL_CAVE_LORELEI
        [140] = { layout = 27, x = 7, y = 4, type = 0 }, -- field: FLAG_HIDE_LORELEI_IN_HER_HOUSE
        [141] = { layout = 278, x = 10, y = 15, type = 0 }, -- field: FLAG_HIDE_ICEFALL_CAVE_ROCKETS
        [142] = { layout = 235, x = 24, y = 25, type = 0 }, -- field: FLAG_HIDE_RUIN_VALLEY_SCIENTIST
        [143] = { layout = 296, x = 7, y = 7, type = 0 }, -- field: FLAG_HIDE_SAPPHIRE
        [144] = { layout = 296, x = 5, y = 9, type = 0 }, -- field: FLAG_HIDE_DOTTED_HOLE_SCIENTIST
        [145] = { layout = 214, x = 8, y = 24, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_LONE_BIKER
        [147] = { layout = 312, x = 5, y = 5, type = 0 }, -- field: FLAG_HIDE_LOST_CAVE_SELPHY
        [148] = { layout = 228, x = 39, y = 9, type = 0 }, -- field: FLAG_HIDE_RESORT_GORGEOUS_SELPHY
        [149] = { layout = 17, x = 4, y = 4, type = 0 }, -- field: FLAG_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY
        [150] = { layout = 17, x = 6, y = 2, type = 0 }, -- field: FLAG_HIDE_SELPHYS_BUTLER
        [151] = { layout = 215, x = 8, y = 25, type = 0 }, -- field: FLAG_HIDE_FOUR_ISLAND_RIVAL
        [152] = { layout = 8, x = 5, y = 5, type = 0, floor = "1F" }, -- field: FLAG_HIDE_SIX_ISLAND_POKECENTER_RIVAL
        [153] = { layout = 324, x = 15, y = 3, type = 0 }, -- field: FLAG_HIDE_DEOXYS
        [154] = { layout = 324, x = 15, y = 12, type = 0 }, -- field: FLAG_HIDE_BIRTH_ISLAND_METEORITE
        [155] = { layout = 328, x = 10, y = 15, type = 0 }, -- field: FLAG_HIDE_LUGIA
        [156] = { layout = 327, x = 9, y = 6, type = 0 }, -- field: FLAG_HIDE_HO_OH
        [157] = { layout = 8, x = 2, y = 1, type = 0, floor = "1F" }, -- field: FLAG_HIDE_POSTGAME_GOSSIPERS
        [158] = { layout = 167, x = 5, y = 6, type = 0, floor = "2F" }, -- field: FLAG_HIDE_FAME_CHECKER_ERIKA_JOURNALS
        [159] = { layout = 183, x = 4, y = 1, type = 0 }, -- field: FLAG_HIDE_FAME_CHECKER_KOGA_JOURNAL
        [160] = { layout = 8, x = 3, y = 1, type = 0, floor = "1F" }, -- field: FLAG_HIDE_FAME_CHECKER_LT_SURGE_JOURNAL
        [161] = { layout = 66, x = 25, y = 7, type = 0 }, -- field: FLAG_HIDE_VERMILION_CITY_OAKS_AIDE
        [162] = { layout = 8, x = 11, y = 5, type = 0, floor = "1F" }, -- field: FLAG_HIDE_CINNABAR_POKECENTER_BILL
        [163] = { layout = 70, x = 11, y = 6, type = 0 }, -- field: FLAG_HIDE_CREDITS_RIVAL
        [164] = { layout = 70, x = 11, y = 6, type = 0 }, -- field: FLAG_HIDE_CREDITS_OAK
        [165] = { layout = 27, x = 9, y = 4, type = 0 }, -- field: FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL
        [166] = { layout = 27, x = 10, y = 4, type = 0 }, -- field: FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL
        [167] = { layout = 27, x = 0, y = 5, type = 0 }, -- field: FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL
        [168] = { layout = 27, x = 0, y = 3, type = 0 }, -- field: FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL
        [169] = { layout = 27, x = 1, y = 5, type = 0 }, -- field: FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL
        [170] = { layout = 27, x = 10, y = 0, type = 0 }, -- field: FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL
        [171] = { layout = 27, x = 9, y = 0, type = 0 }, -- field: FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL
        [172] = { layout = 27, x = 9, y = 6, type = 0 }, -- field: FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL
        [173] = { layout = 114, x = 16, y = 14, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_MISC_KANTO_ROCKETS
        [174] = { layout = 8, x = 3, y = 1, type = 0, floor = "1F" }, -- field: FLAG_HIDE_SAFFRON_CITY_POKECENTER_SABRINA_JOURNALS
        [175] = { layout = 61, x = 5, y = 13, type = 0 }, -- field: FLAG_HIDE_ABANDONED_BALL_1
        [176] = { layout = 61, x = 6, y = 13, type = 0 }, -- field: FLAG_HIDE_ABANDONED_BALL_2
        [177] = { layout = 61, x = 7, y = 13, type = 0 }, -- field: FLAG_HIDE_ABANDONED_BALL_3
        [178] = { layout = 61, x = 8, y = 13, type = 0 }, -- field: FLAG_HIDE_ABANDONED_BALL_4
        [179] = { layout = 61, x = 9, y = 13, type = 0 }, -- field: FLAG_HIDE_ABANDONED_BALL_5
        [342] = { layout = 100, x = 5, y = 41, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_FOREST_POKE_BALL
        [343] = { layout = 100, x = 40, y = 21, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_FOREST_ANTIDOTE
        [344] = { layout = 100, x = 21, y = 34, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_FOREST_POTION
        [345] = { layout = 97, x = 2, y = 22, type = 0, floor = "1F" }, -- field: FLAG_HIDE_MT_MOON_1F_PARALYZE_HEAL
        [346] = { layout = 97, x = 11, y = 35, type = 1, floor = "1F" }, -- TM: FLAG_HIDE_MT_MOON_1F_TM09
        [347] = { layout = 97, x = 26, y = 32, type = 0, floor = "1F" }, -- field: FLAG_HIDE_MT_MOON_1F_POTION
        [348] = { layout = 97, x = 42, y = 35, type = 0, floor = "1F" }, -- field: FLAG_HIDE_MT_MOON_1F_RARE_CANDY
        [349] = { layout = 97, x = 44, y = 21, type = 0, floor = "1F" }, -- field: FLAG_HIDE_MT_MOON_1F_ESCAPE_ROPE
        [350] = { layout = 97, x = 3, y = 2, type = 0, floor = "1F" }, -- field: FLAG_HIDE_MT_MOON_1F_MOON_STONE
        [351] = { layout = 99, x = 30, y = 26, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_MT_MOON_B2F_STAR_PIECE
        [352] = { layout = 99, x = 35, y = 5, type = 1, floor = "B2F" }, -- TM: FLAG_HIDE_MT_MOON_B2F_TM46
        [353] = { layout = 75, x = 67, y = 5, type = 1 }, -- TM: FLAG_HIDE_ROUTE4_TM05
        [354] = { layout = 95, x = 11, y = 4, type = 1 }, -- TM: FLAG_HIDE_ROUTE24_TM45
        [355] = { layout = 96, x = 26, y = 2, type = 1 }, -- TM: FLAG_HIDE_ROUTE25_TM43
        [356] = { layout = 159, x = 5, y = 7, type = 1 }, -- TM: FLAG_HIDE_SSANNE_1F_ROOM2_TM31
        [357] = { layout = 160, x = 3, y = 3, type = 0 }, -- field: FLAG_HIDE_SSANNE_2F_ROOM2_STARDUST
        [358] = { layout = 160, x = 2, y = 4, type = 0 }, -- field: FLAG_HIDE_SSANNE_2F_ROOM4_X_ATTACK
        [359] = { layout = 160, x = 3, y = 2, type = 1 }, -- TM: FLAG_HIDE_SSANNE_B1F_ROOM2_TM44
        [360] = { layout = 160, x = 1, y = 5, type = 0 }, -- field: FLAG_HIDE_SSANNE_B1F_ROOM3_ETHER
        [361] = { layout = 160, x = 2, y = 2, type = 0 }, -- field: FLAG_HIDE_SSANNE_B1F_ROOM5_SUPER_POTION
        [362] = { layout = 153, x = 1, y = 10, type = 0 }, -- field: FLAG_HIDE_SSANNE_KITCHEN_GREAT_BALL
        [363] = { layout = 80, x = 12, y = 17, type = 1 }, -- TM: FLAG_HIDE_ROUTE9_TM40
        [364] = { layout = 111, x = 5, y = 16, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B1F_ESCAPE_ROPE
        [365] = { layout = 111, x = 1, y = 22, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B1F_HYPER_POTION
        [366] = { layout = 112, x = 15, y = 3, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B2F_X_SPEED
        [367] = { layout = 112, x = 2, y = 5, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B2F_MOON_STONE
        [368] = { layout = 112, x = 5, y = 7, type = 1, floor = "B2F" }, -- TM: FLAG_HIDE_ROCKET_HIDEOUT_B2F_TM12
        [369] = { layout = 112, x = 0, y = 14, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B2F_SUPER_POTION
        [370] = { layout = 113, x = 12, y = 12, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B3F_RARE_CANDY
        [371] = { layout = 113, x = 19, y = 14, type = 1, floor = "B3F" }, -- TM: FLAG_HIDE_ROCKET_HIDEOUT_B3F_TM21
        [372] = { layout = 114, x = 1, y = 6, type = 1, floor = "B4F" }, -- TM: FLAG_HIDE_ROCKET_HIDEOUT_B4F_TM49
        [373] = { layout = 114, x = 4, y = 14, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B4F_MAX_ETHER
        [374] = { layout = 114, x = 6, y = 23, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B4F_CALCIUM
        [375] = { layout = 146, x = 13, y = 2, type = 0, floor = "3F" }, -- field: FLAG_HIDE_POKEMON_TOWER_3F_ESCAPE_ROPE
        [376] = { layout = 147, x = 12, y = 11, type = 0, floor = "4F" }, -- field: FLAG_HIDE_POKEMON_TOWER_4F_ELIXIR
        [377] = { layout = 147, x = 8, y = 11, type = 0, floor = "4F" }, -- field: FLAG_HIDE_POKEMON_TOWER_4F_AWAKENING
        [378] = { layout = 147, x = 11, y = 16, type = 0, floor = "4F" }, -- field: FLAG_HIDE_POKEMON_TOWER_4F_GREAT_BALL
        [379] = { layout = 148, x = 6, y = 16, type = 0, floor = "5F" }, -- field: FLAG_HIDE_POKEMON_TOWER_5F_NUGGET
        [380] = { layout = 149, x = 5, y = 15, type = 0, floor = "6F" }, -- field: FLAG_HIDE_POKEMON_TOWER_6F_RARE_CANDY
        [381] = { layout = 149, x = 15, y = 15, type = 0, floor = "6F" }, -- field: FLAG_HIDE_POKEMON_TOWER_6F_X_ACCURACY
        [382] = { layout = 83, x = 18, y = 36, type = 1 }, -- TM: FLAG_HIDE_ROUTE12_TM48
        [383] = { layout = 83, x = 9, y = 101, type = 0 }, -- field: FLAG_HIDE_ROUTE12_IRON
        [384] = { layout = 86, x = 20, y = 6, type = 1 }, -- TM: FLAG_HIDE_ROUTE15_TM18
        [385] = { layout = 130, x = 24, y = 15, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_CENTER_NUGGET
        [386] = { layout = 131, x = 13, y = 12, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_EAST_MAX_POTION
        [387] = { layout = 131, x = 37, y = 15, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_EAST_FULL_RESTORE
        [388] = { layout = 131, x = 31, y = 18, type = 1 }, -- TM: FLAG_HIDE_SAFARI_ZONE_EAST_TM11
        [389] = { layout = 131, x = 36, y = 17, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_EAST_LEAF_STONE
        [390] = { layout = 132, x = 33, y = 5, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_NORTH_PROTEIN
        [391] = { layout = 132, x = 28, y = 9, type = 1 }, -- TM: FLAG_HIDE_SAFARI_ZONE_NORTH_TM47
        [392] = { layout = 133, x = 17, y = 13, type = 1 }, -- TM: FLAG_HIDE_SAFARI_ZONE_WEST_TM32
        [393] = { layout = 133, x = 28, y = 14, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_WEST_GOLD_TEETH
        [394] = { layout = 133, x = 16, y = 27, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_WEST_MAX_POTION
        [395] = { layout = 133, x = 27, y = 24, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_WEST_MAX_REVIVE
        [396] = { layout = 117, x = 8, y = 10, type = 0, floor = "3F" }, -- field: FLAG_HIDE_SILPH_CO_3F_HYPER_POTION
        [397] = { layout = 118, x = 3, y = 11, type = 0, floor = "4F" }, -- field: FLAG_HIDE_SILPH_CO_4F_MAX_REVIVE
        [398] = { layout = 118, x = 4, y = 12, type = 0, floor = "4F" }, -- field: FLAG_HIDE_SILPH_CO_4F_ESCAPE_ROPE
        [399] = { layout = 118, x = 2, y = 13, type = 0, floor = "4F" }, -- field: FLAG_HIDE_SILPH_CO_4F_FULL_HEAL
        [400] = { layout = 119, x = 4, y = 9, type = 0, floor = "5F" }, -- field: FLAG_HIDE_SILPH_CO_5F_PROTEIN
        [401] = { layout = 119, x = 1, y = 18, type = 1, floor = "5F" }, -- TM: FLAG_HIDE_SILPH_CO_5F_TM01
        [402] = { layout = 119, x = 22, y = 21, type = 0, floor = "5F" }, -- field: FLAG_HIDE_SILPH_CO_5F_CARD_KEY
        [403] = { layout = 120, x = 2, y = 14, type = 0, floor = "6F" }, -- field: FLAG_HIDE_SILPH_CO_6F_HP_UP
        [404] = { layout = 120, x = 1, y = 17, type = 0, floor = "6F" }, -- field: FLAG_HIDE_SILPH_CO_6F_X_SPECIAL
        [405] = { layout = 121, x = 0, y = 12, type = 0, floor = "7F" }, -- field: FLAG_HIDE_SILPH_CO_7F_CALCIUM
        [406] = { layout = 121, x = 30, y = 11, type = 1, floor = "7F" }, -- TM: FLAG_HIDE_SILPH_CO_7F_TM08
        [407] = { layout = 124, x = 5, y = 15, type = 0, floor = "10F" }, -- field: FLAG_HIDE_SILPH_CO_10F_CARBOS
        [408] = { layout = 124, x = 2, y = 15, type = 0, floor = "10F" }, -- field: FLAG_HIDE_SILPH_CO_10F_ULTRA_BALL
        [409] = { layout = 124, x = 3, y = 17, type = 0, floor = "10F" }, -- field: FLAG_HIDE_SILPH_CO_10F_RARE_CANDY
        [410] = { layout = 151, x = 7, y = 27, type = 0 }, -- field: FLAG_HIDE_POWER_PLANT_MAX_POTION
        [411] = { layout = 151, x = 40, y = 22, type = 1 }, -- TM: FLAG_HIDE_POWER_PLANT_TM17
        [412] = { layout = 151, x = 46, y = 37, type = 1 }, -- TM: FLAG_HIDE_POWER_PLANT_TM25
        [413] = { layout = 151, x = 45, y = 4, type = 0 }, -- field: FLAG_HIDE_POWER_PLANT_THUNDER_STONE
        [414] = { layout = 151, x = 26, y = 22, type = 0 }, -- field: FLAG_HIDE_POWER_PLANT_ELIXIR
        [415] = { layout = 126, x = 29, y = 32, type = 0, floor = "1F" }, -- field: FLAG_HIDE_POKEMON_MANSION_1F_CARBOS
        [416] = { layout = 126, x = 22, y = 6, type = 0, floor = "1F" }, -- field: FLAG_HIDE_POKEMON_MANSION_1F_ESCAPE_ROPE
        [417] = { layout = 127, x = 36, y = 8, type = 0, floor = "2F" }, -- field: FLAG_HIDE_POKEMON_MANSION_2F_CALCIUM
        [418] = { layout = 128, x = 9, y = 19, type = 0, floor = "3F" }, -- field: FLAG_HIDE_POKEMON_MANSION_3F_MAX_POTION
        [419] = { layout = 128, x = 32, y = 6, type = 0, floor = "3F" }, -- field: FLAG_HIDE_POKEMON_MANSION_3F_IRON
        [420] = { layout = 129, x = 23, y = 4, type = 1, floor = "B1F" }, -- TM: FLAG_HIDE_POKEMON_MANSION_B1F_TM14
        [421] = { layout = 129, x = 2, y = 29, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_POKEMON_MANSION_B1F_FULL_RESTORE
        [423] = { layout = 129, x = 6, y = 21, type = 1, floor = "B1F" }, -- TM: FLAG_HIDE_POKEMON_MANSION_B1F_TM22
        [424] = { layout = 129, x = 5, y = 7, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_POKEMON_MANSION_B1F_SECRET_KEY
        [425] = { layout = 108, x = 12, y = 3, type = 0, floor = "1F" }, -- field: FLAG_HIDE_VICTORY_ROAD_1F_RARE_CANDY
        [426] = { layout = 108, x = 14, y = 1, type = 1, floor = "1F" }, -- TM: FLAG_HIDE_VICTORY_ROAD_1F_TM02
        [427] = { layout = 109, x = 17, y = 6, type = 0, floor = "2F" }, -- field: FLAG_HIDE_VICTORY_ROAD_2F_GUARD_SPEC
        [428] = { layout = 109, x = 40, y = 7, type = 1, floor = "2F" }, -- TM: FLAG_HIDE_VICTORY_ROAD_2F_TM07
        [429] = { layout = 109, x = 25, y = 13, type = 0, floor = "2F" }, -- field: FLAG_HIDE_VICTORY_ROAD_2F_FULL_HEAL
        [430] = { layout = 109, x = 14, y = 13, type = 1, floor = "2F" }, -- TM: FLAG_HIDE_VICTORY_ROAD_2F_TM37
        [431] = { layout = 110, x = 38, y = 7, type = 0, floor = "3F" }, -- field: FLAG_HIDE_VICTORY_ROAD_3F_MAX_REVIVE
        [432] = { layout = 110, x = 12, y = 9, type = 1, floor = "3F" }, -- TM: FLAG_HIDE_VICTORY_ROAD_3F_TM50
        [433] = { layout = 134, x = 25, y = 5, type = 0, floor = "1F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_1F_MAX_ELIXIR
        [434] = { layout = 134, x = 7, y = 3, type = 0, floor = "1F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_1F_NUGGET
        [435] = { layout = 134, x = 11, y = 16, type = 0, floor = "1F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_1F_FULL_RESTORE
        [436] = { layout = 135, x = 33, y = 12, type = 0, floor = "2F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_2F_FULL_RESTORE
        [437] = { layout = 135, x = 9, y = 18, type = 0, floor = "2F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_2F_PP_UP
        [438] = { layout = 135, x = 29, y = 16, type = 0, floor = "2F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_2F_ULTRA_BALL
        [439] = { layout = 136, x = 32, y = 2, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_B1F_MAX_REVIVE
        [440] = { layout = 136, x = 31, y = 9, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_CERULEAN_CAVE_B1F_ULTRA_BALL
        [441] = { layout = 183, x = 11, y = 5, type = 0 }, -- field: FLAG_HIDE_FUCHSIA_CITY_WARDENS_HOUSE_RARE_CANDY
        [442] = { layout = 213, x = 39, y = 16, type = 0 }, -- field: FLAG_HIDE_TWO_ISLAND_REVIVE
        [443] = { layout = 214, x = 18, y = 17, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_ZINC
        [444] = { layout = 75, x = 19, y = 6, type = 0 }, -- field: FLAG_HIDE_JAMES
        [445] = { layout = 100, x = 41, y = 55, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_FOREST_GATEKEEPER
        [446] = { layout = 100, x = 49, y = 60, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_FOREST_POTION_2
        [447] = { layout = 99, x = 24, y = 6, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_MT_MOON_B2F_REVIVE
        [448] = { layout = 99, x = 3, y = 11, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_MT_MOON_B2F_ANTIDOTE
        [449] = { layout = 82, x = 42, y = 12, type = 0 }, -- field: FLAG_HIDE_ROUTE11_X_DEFEND
        [450] = { layout = 80, x = 65, y = 17, type = 0 }, -- field: FLAG_HIDE_ROUTE9_BURN_HEAL
        [451] = { layout = 137, x = 37, y = 5, type = 0, floor = "1F" }, -- field: FLAG_HIDE_ROCK_TUNNEL_1F_REPEL
        [452] = { layout = 137, x = 33, y = 22, type = 0, floor = "1F" }, -- field: FLAG_HIDE_ROCK_TUNNEL_1F_PEARL
        [453] = { layout = 137, x = 22, y = 22, type = 0, floor = "1F" }, -- field: FLAG_HIDE_ROCK_TUNNEL_1F_ESCAPE_ROPE
        [454] = { layout = 138, x = 2, y = 37, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_ROCK_TUNNEL_B1F_REVIVE
        [455] = { layout = 138, x = 9, y = 2, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_ROCK_TUNNEL_B1F_MAX_ETHER
        [456] = { layout = 122, x = 24, y = 8, type = 0, floor = "8F" }, -- field: FLAG_HIDE_SILPH_CO_8F_IRON
        [457] = { layout = 125, x = 16, y = 18, type = 0, floor = "11F" }, -- field: FLAG_HIDE_SILPH_CO_11F_ZINC
        [458] = { layout = 126, x = 27, y = 15, type = 0, floor = "1F" }, -- field: FLAG_HIDE_POKEMON_MANSION_1F_PROTEIN
        [459] = { layout = 127, x = 18, y = 23, type = 0, floor = "2F" }, -- field: FLAG_HIDE_POKEMON_MANSION_2F_ZINC
        [460] = { layout = 127, x = 35, y = 17, type = 0, floor = "2F" }, -- field: FLAG_HIDE_POKEMON_MANSION_2F_HP_UP
        [461] = { layout = 62, x = 17, y = 5, type = 0 }, -- field: FLAG_HIDE_VIRIDIAN_CITY_POTION
        [462] = { layout = 82, x = 63, y = 13, type = 0 }, -- field: FLAG_HIDE_ROUTE11_GREAT_BALL
        [463] = { layout = 82, x = 13, y = 3, type = 0 }, -- field: FLAG_HIDE_ROUTE11_AWAKENING
        [465] = { layout = 67, x = 5, y = 3, type = 0 }, -- field: FLAG_HIDE_CELADON_CITY_ETHER
        [466] = { layout = 113, x = 14, y = 24, type = 0, floor = "B3F" }, -- field: FLAG_HIDE_ROCKET_HIDEOUT_B3F_BLACK_GLASSES
        [467] = { layout = 132, x = 29, y = 17, type = 0 }, -- field: FLAG_HIDE_SAFARI_ZONE_NORTH_QUICK_CLAW
        [468] = { layout = 139, x = 11, y = 8, type = 0, floor = "1F" }, -- field: FLAG_HIDE_SEAFOAM_ISLANDS_1F_ICE_HEAL
        [469] = { layout = 140, x = 19, y = 18, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_SEAFOAM_ISLANDS_B1F_WATER_STONE
        [470] = { layout = 140, x = 24, y = 14, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_SEAFOAM_ISLANDS_B1F_REVIVE
        [471] = { layout = 141, x = 18, y = 15, type = 0, floor = "B2F" }, -- field: FLAG_HIDE_SEAFOAM_ISLANDS_B2F_BIG_PEARL
        [472] = { layout = 143, x = 22, y = 19, type = 0, floor = "B4F" }, -- field: FLAG_HIDE_SEAFOAM_ISLANDS_B4F_ULTRA_BALL
        [473] = { layout = 215, x = 5, y = 6, type = 0 }, -- field: FLAG_HIDE_FOUR_ISLAND_STAR_PIECE
        [474] = { layout = 215, x = 32, y = 19, type = 0 }, -- field: FLAG_HIDE_FOUR_ISLAND_STARDUST
        [475] = { layout = 219, x = 15, y = 70, type = 0 }, -- field: FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_ETHER
        [476] = { layout = 219, x = 17, y = 103, type = 0 }, -- field: FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_MAX_REPEL
        [477] = { layout = 219, x = 18, y = 114, type = 0 }, -- field: FLAG_HIDE_ONE_ISLAND_KINDLE_ROAD_CARBOS
        [478] = { layout = 230, x = 12, y = 11, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_MEADOW_MAX_POTION
        [479] = { layout = 230, x = 3, y = 22, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_MEADOW_PP_UP
        [480] = { layout = 231, x = 4, y = 47, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_MEMORIAL_PILLAR_METAL_COAT
        [481] = { layout = 232, x = 11, y = 16, type = 0 }, -- field: FLAG_HIDE_SIX_ISLAND_OUTCAST_ISLAND_PP_UP
        [482] = { layout = 234, x = 17, y = 19, type = 0 }, -- field: FLAG_HIDE_SIX_ISLAND_WATER_PATH_ELIXIR
        [483] = { layout = 234, x = 17, y = 87, type = 0 }, -- field: FLAG_HIDE_SIX_ISLAND_WATER_PATH_DRAGON_SCALE
        [484] = { layout = 235, x = 19, y = 11, type = 0 }, -- field: FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_FULL_RESTORE
        [485] = { layout = 235, x = 5, y = 33, type = 0 }, -- field: FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_HP_UP
        [486] = { layout = 235, x = 43, y = 32, type = 0 }, -- field: FLAG_HIDE_SIX_ISLAND_RUIN_VALLEY_SUN_STONE
        [487] = { layout = 238, x = 18, y = 45, type = 0 }, -- field: FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_KINGS_ROCK
        [488] = { layout = 238, x = 7, y = 38, type = 0 }, -- field: FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_MAX_ELIXIR
        [489] = { layout = 238, x = 17, y = 23, type = 0 }, -- field: FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_NUGGET
        [490] = { layout = 252, x = 12, y = 5, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ETHER
        [491] = { layout = 252, x = 27, y = 11, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_FULL_HEAL
        [492] = { layout = 252, x = 12, y = 43, type = 0 }, -- field: FLAG_HIDE_THREE_ISLAND_BERRY_FOREST_MAX_ELIXIR
        [493] = { layout = 262, x = 13, y = 6, type = 0 }, -- field: FLAG_HIDE_MT_EMBER_EXTERIOR_ULTRA_BALL
        [494] = { layout = 262, x = 38, y = 10, type = 0 }, -- field: FLAG_HIDE_MT_EMBER_EXTERIOR_FIRE_STONE
        [495] = { layout = 262, x = 48, y = 20, type = 0 }, -- field: FLAG_HIDE_MT_EMBER_EXTERIOR_DIRE_HIT
        [496] = { layout = 276, x = 11, y = 7, type = 0, floor = "1F" }, -- field: FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_ULTRA_BALL
        [497] = { layout = 276, x = 12, y = 16, type = 1, floor = "1F" }, -- TM: FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_1F_HM07
        [498] = { layout = 277, x = 10, y = 14, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_FULL_RESTORE
        [499] = { layout = 277, x = 21, y = 7, type = 0, floor = "B1F" }, -- field: FLAG_HIDE_FOUR_ISLAND_ICEFALL_CAVE_B1F_NEVER_MELT_ICE
        [500] = { layout = 274, x = 8, y = 25, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_BIG_PEARL
        [501] = { layout = 274, x = 17, y = 3, type = 1 }, -- TM: FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_TM36
        [502] = { layout = 274, x = 1, y = 16, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_PEARL
        [503] = { layout = 274, x = 4, y = 5, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_ROCKET_WAREHOUSE_UP_GRADE
        [504] = { layout = 312, x = 5, y = 2, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM10_SILK_SCARF
        [505] = { layout = 313, x = 5, y = 5, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM11_LAX_INCENSE
        [506] = { layout = 314, x = 5, y = 5, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM12_SEA_INCENSE
        [507] = { layout = 315, x = 5, y = 5, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM13_MAX_REVIVE
        [508] = { layout = 316, x = 5, y = 5, type = 0 }, -- field: FLAG_HIDE_FIVE_ISLAND_LOST_CAVE_ROOM14_RARE_CANDY
        [509] = { layout = 11, x = 6, y = 4, type = 0 }, -- field: FLAG_HIDE_SEVEN_ISLAND_SEVAULT_CANYON_HOUSE_LUCKY_PUNCH
        [510] = { layout = 118, x = 30, y = 18, type = 1, floor = "4F" }, -- TM: FLAG_HIDE_SILPH_CO_4F_TM41
        [1000] = { layout = 100, x = 3, y = 22, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_POTION
        [1001] = { layout = 100, x = 28, y = 57, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_ANTIDOTE
        [1002] = { layout = 99, x = 20, y = 16, type = 2, floor = "B2F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B2F_MOON_STONE
        [1003] = { layout = 99, x = 39, y = 11, type = 2, floor = "B2F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B2F_ETHER
        [1004] = { layout = 96, x = 14, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE25_ELIXIR
        [1005] = { layout = 96, x = 58, y = 6, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE25_ETHER
        [1006] = { layout = 80, x = 15, y = 7, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE9_ETHER
        [1008] = { layout = 105, x = 21, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SSANNE_B1F_CORRIDOR_HYPER_POTION
        [1009] = { layout = 81, x = 10, y = 19, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE10_SUPER_POTION
        [1010] = { layout = 81, x = 12, y = 40, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE10_MAX_ETHER
        [1011] = { layout = 111, x = 16, y = 17, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B1F_PP_UP
        [1012] = { layout = 113, x = 1, y = 3, type = 2, floor = "B3F" }, -- hidden: FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B3F_NUGGET
        [1013] = { layout = 114, x = 22, y = 6, type = 2, floor = "B4F" }, -- hidden: FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NEST_BALL
        [1014] = { layout = 148, x = 7, y = 3, type = 2, floor = "5F" }, -- hidden: FLAG_HIDDEN_ITEM_POKEMON_TOWER_5F_BIG_MUSHROOM
        [1015] = { layout = 84, x = 23, y = 14, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE13_PP_UP
        [1017] = { layout = 88, x = 18, y = 83, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE17_RARE_CANDY
        [1018] = { layout = 88, x = 10, y = 53, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE17_FULL_RESTORE
        [1019] = { layout = 88, x = 4, y = 68, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE17_PP_UP
        [1020] = { layout = 88, x = 4, y = 125, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE17_MAX_REVIVE
        [1021] = { layout = 88, x = 14, y = 157, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE17_MAX_ELIXIR
        [1022] = { layout = 130, x = 27, y = 15, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SAFARI_ZONE_CENTER_LEAF_STONE
        [1023] = { layout = 133, x = 13, y = 11, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SAFARI_ZONE_WEST_REVIVE
        [1024] = { layout = 119, x = 13, y = 16, type = 2, floor = "5F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_5F_ELIXIR
        [1025] = { layout = 123, x = 11, y = 14, type = 2, floor = "9F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_9F_MAX_POTION
        [1027] = { layout = 151, x = 29, y = 16, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_POWER_PLANT_MAX_ELIXIR
        [1028] = { layout = 151, x = 8, y = 12, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_POWER_PLANT_THUNDER_STONE
        [1029] = { layout = 142, x = 5, y = 12, type = 2, floor = "B3F" }, -- hidden: FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B3F_NUGGET
        [1030] = { layout = 143, x = 13, y = 8, type = 2, floor = "B4F" }, -- hidden: FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B4F_WATER_STONE
        [1031] = { layout = 126, x = 2, y = 21, type = 2, floor = "1F" }, -- hidden: FLAG_HIDDEN_ITEM_POKEMON_MANSION_1F_MOON_STONE
        [1032] = { layout = 128, x = 36, y = 13, type = 2, floor = "3F" }, -- hidden: FLAG_HIDDEN_ITEM_POKEMON_MANSION_3F_RARE_CANDY
        [1033] = { layout = 129, x = 35, y = 5, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_POKEMON_MANSION_B1F_ELIXIR
        [1034] = { layout = 94, x = 19, y = 42, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_FULL_RESTORE
        [1035] = { layout = 94, x = 20, y = 72, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_ULTRA_BALL
        [1036] = { layout = 94, x = 11, y = 101, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_MAX_ETHER
        [1037] = { layout = 108, x = 12, y = 12, type = 2, floor = "1F" }, -- hidden: FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL
        [1038] = { layout = 108, x = 16, y = 1, type = 2, floor = "1F" }, -- hidden: FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_FULL_RESTORE
        [1039] = { layout = 134, x = 12, y = 2, type = 2, floor = "1F" }, -- hidden: FLAG_HIDDEN_ITEM_CERULEAN_CAVE_1F_ULTRA_BALL
        [1041] = { layout = 82, x = 58, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE11_ESCAPE_ROPE
        [1042] = { layout = 83, x = 18, y = 57, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE12_HYPER_POTION
        [1047] = { layout = 67, x = 55, y = 20, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_PP_UP
        [1048] = { layout = 66, x = 14, y = 11, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_VERMILION_CITY_MAX_ETHER
        [1050] = { layout = 75, x = 43, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE4_GREAT_BALL
        [1051] = { layout = 25, x = 2, y = 4, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS
        [1052] = { layout = 25, x = 3, y = 8, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_2
        [1053] = { layout = 25, x = 2, y = 11, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_3
        [1054] = { layout = 25, x = 6, y = 12, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_4
        [1055] = { layout = 25, x = 9, y = 9, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_5
        [1056] = { layout = 25, x = 8, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_6
        [1057] = { layout = 25, x = 10, y = 4, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_7
        [1058] = { layout = 25, x = 13, y = 3, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_8
        [1059] = { layout = 25, x = 15, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_9
        [1060] = { layout = 25, x = 17, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_10
        [1061] = { layout = 25, x = 15, y = 13, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_11
        [1062] = { layout = 25, x = 12, y = 12, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_CELADON_CITY_GAME_CORNER_COINS_12
        [1063] = { layout = 238, x = 15, y = 66, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_CHERI_BERRY
        [1064] = { layout = 239, x = 8, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_4
        [1065] = { layout = 239, x = 33, y = 10, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE
        [1066] = { layout = 239, x = 86, y = 9, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_2
        [1067] = { layout = 239, x = 125, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_3
        [1068] = { layout = 274, x = 27, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NEST_BALL
        [1069] = { layout = 274, x = 7, y = 16, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NET_BALL
        [1084] = { layout = 98, x = 46, y = 2, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM
        [1085] = { layout = 98, x = 26, y = 2, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_2
        [1086] = { layout = 98, x = 39, y = 34, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_3
        [1087] = { layout = 98, x = 24, y = 35, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM
        [1088] = { layout = 98, x = 6, y = 12, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_2
        [1089] = { layout = 98, x = 25, y = 34, type = 2, floor = "B1F" }, -- hidden: FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_3
        [1090] = { layout = 252, x = 31, y = 25, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAZZ_BERRY
        [1091] = { layout = 252, x = 15, y = 15, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_BLUK_BERRY
        [1092] = { layout = 252, x = 25, y = 24, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_NANAB_BERRY
        [1093] = { layout = 252, x = 11, y = 24, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_WEPEAR_BERRY
        [1094] = { layout = 252, x = 37, y = 18, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ORAN_BERRY
        [1095] = { layout = 252, x = 14, y = 23, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHERI_BERRY
        [1096] = { layout = 252, x = 47, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHESTO_BERRY
        [1097] = { layout = 252, x = 7, y = 30, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PECHA_BERRY
        [1098] = { layout = 252, x = 16, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAWST_BERRY
        [1099] = { layout = 252, x = 25, y = 6, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ASPEAR_BERRY
        [1100] = { layout = 252, x = 46, y = 32, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PERSIM_BERRY
        [1101] = { layout = 252, x = 43, y = 16, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PINAP_BERRY
        [1102] = { layout = 252, x = 8, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_LUM_BERRY
        [1103] = { layout = 220, x = 8, y = 20, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST
        [1104] = { layout = 220, x = 13, y = 27, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST_2
        [1105] = { layout = 220, x = 11, y = 31, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL
        [1106] = { layout = 220, x = 9, y = 34, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL_2
        [1107] = { layout = 220, x = 15, y = 22, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL
        [1108] = { layout = 220, x = 16, y = 33, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL_2
        [1109] = { layout = 220, x = 15, y = 29, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STAR_PIECE
        [1110] = { layout = 220, x = 8, y = 27, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_BIG_PEARL
        [1111] = { layout = 221, x = 15, y = 13, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_RARE_CANDY
        [1112] = { layout = 63, x = 6, y = 3, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_PEWTER_CITY_POKE_BALL
        [1113] = { layout = 74, x = 26, y = 9, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE3_ORAN_BERRY
        [1114] = { layout = 75, x = 5, y = 4, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE4_PERSIM_BERRY
        [1115] = { layout = 95, x = 19, y = 4, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE24_PECHA_BERRY
        [1116] = { layout = 96, x = 33, y = 8, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE25_ORAN_BERRY
        [1117] = { layout = 96, x = 40, y = 3, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE25_BLUK_BERRY
        [1118] = { layout = 77, x = 5, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE6_SITRUS_BERRY
        [1119] = { layout = 77, x = 19, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE6_RARE_CANDY
        [1120] = { layout = 153, x = 14, y = 4, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_PECHA_BERRY
        [1121] = { layout = 153, x = 14, y = 6, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHERI_BERRY
        [1122] = { layout = 153, x = 14, y = 8, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHESTO_BERRY
        [1123] = { layout = 80, x = 63, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE9_RARE_CANDY
        [1125] = { layout = 81, x = 17, y = 29, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE10_PERSIM_BERRY
        [1126] = { layout = 81, x = 6, y = 26, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE10_CHERI_BERRY
        [1127] = { layout = 79, x = 42, y = 10, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE8_RAWST_BERRY
        [1128] = { layout = 79, x = 38, y = 11, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE8_LUM_BERRY
        [1129] = { layout = 79, x = 42, y = 15, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE8_LEPPA_BERRY
        [1130] = { layout = 83, x = 9, y = 116, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE12_RARE_CANDY
        [1131] = { layout = 83, x = 14, y = 70, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE12_LEFTOVERS
        [1132] = { layout = 87, x = 31, y = 13, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE16_LEFTOVERS
        [1134] = { layout = 114, x = 16, y = 6, type = 2, floor = "B4F" }, -- hidden: FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NET_BALL
        [1135] = { layout = 116, x = 11, y = 21, type = 2, floor = "2F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_2F_ULTRA_BALL
        [1136] = { layout = 117, x = 34, y = 18, type = 2, floor = "3F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_3F_PROTEIN
        [1137] = { layout = 118, x = 35, y = 20, type = 2, floor = "4F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_4F_IRON
        [1138] = { layout = 119, x = 32, y = 9, type = 2, floor = "5F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_5F_PP_UP
        [1139] = { layout = 120, x = 1, y = 8, type = 2, floor = "6F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_6F_CARBOS
        [1140] = { layout = 121, x = 22, y = 11, type = 2, floor = "7F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_7F_ZINC
        [1141] = { layout = 122, x = 29, y = 10, type = 2, floor = "8F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_8F_NUGGET
        [1142] = { layout = 123, x = 5, y = 8, type = 2, floor = "9F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_9F_CALCIUM
        [1143] = { layout = 124, x = 9, y = 9, type = 2, floor = "10F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_10F_HP_UP
        [1144] = { layout = 125, x = 10, y = 18, type = 2, floor = "11F" }, -- hidden: FLAG_HIDDEN_ITEM_SILPH_CO_11F_REVIVE
        [1145] = { layout = 94, x = 3, y = 18, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_LUM_BERRY
        [1146] = { layout = 94, x = 2, y = 29, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_SITRUS_BERRY
        [1147] = { layout = 94, x = 10, y = 67, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_ASPEAR_BERRY
        [1148] = { layout = 94, x = 3, y = 128, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_LEPPA_BERRY
        [1149] = { layout = 85, x = 9, y = 20, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE14_ZINC
        [1150] = { layout = 80, x = 48, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE9_CHESTO_BERRY
        [1151] = { layout = 81, x = 20, y = 57, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE10_NANAB_BERRY
        [1152] = { layout = 78, x = 16, y = 15, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE7_WEPEAR_BERRY
        [1153] = { layout = 91, x = 23, y = 6, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE20_STARDUST
        [1154] = { layout = 92, x = 17, y = 42, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE21_NORTH_PEARL
        [1155] = { layout = 94, x = 9, y = 8, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE23_MAX_ELIXIR
        [1156] = { layout = 75, x = 67, y = 17, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE4_RAZZ_BERRY
        [1157] = { layout = 85, x = 19, y = 53, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_ROUTE14_PINAP_BERRY
        [1158] = { layout = 262, x = 18, y = 17, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_FIRE_STONE
        [1159] = { layout = 150, x = 11, y = 4, type = 2, floor = "7F" }, -- hidden: FLAG_HIDDEN_ITEM_POKEMON_TOWER_7F_SOOTHE_BELL
        [1160] = { layout = 327, x = 9, y = 11, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_NAVEL_ROCK_SUMMIT_SACRED_ASH
        [1161] = { layout = 221, x = 16, y = 28, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_PP_MAX
        [1162] = { layout = 262, x = 8, y = 30, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_ULTRA_BALL
        [1163] = { layout = 300, x = 21, y = 3, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_DUNSPARCE_TUNNEL_NUGGET
        [1164] = { layout = 214, x = 5, y = 13, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_PP_UP
        [1165] = { layout = 222, x = 61, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_MAX_REPEL
        [1166] = { layout = 222, x = 44, y = 12, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_PEARL
        [1167] = { layout = 222, x = 33, y = 7, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_STARDUST
        [1168] = { layout = 215, x = 22, y = 34, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FOUR_ISLAND_PEARL
        [1169] = { layout = 215, x = 6, y = 21, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FOUR_ISLAND_ULTRA_BALL
        [1170] = { layout = 231, x = 8, y = 52, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BIG_PEARL
        [1171] = { layout = 231, x = 15, y = 7, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_RAZZ_BERRY
        [1172] = { layout = 231, x = 17, y = 22, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_SITRUS_BERRY
        [1173] = { layout = 231, x = 14, y = 25, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BLUK_BERRY
        [1174] = { layout = 228, x = 10, y = 7, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_NEST_BALL
        [1175] = { layout = 228, x = 27, y = 11, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST
        [1176] = { layout = 228, x = 40, y = 12, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STAR_PIECE
        [1177] = { layout = 228, x = 27, y = 5, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST_2
        [1178] = { layout = 232, x = 16, y = 23, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_STAR_PIECE
        [1179] = { layout = 232, x = 6, y = 24, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_NET_BALL
        [1180] = { layout = 233, x = 12, y = 9, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_GREEN_PATH_ULTRA_BALL
        [1181] = { layout = 234, x = 15, y = 76, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ASPEAR_BERRY
        [1182] = { layout = 234, x = 3, y = 8, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ORAN_BERRY
        [1183] = { layout = 234, x = 13, y = 63, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_PINAP_BERRY
        [1184] = { layout = 218, x = 9, y = 7, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SIX_ISLAND_LEPPA_BERRY
        [1185] = { layout = 236, x = 49, y = 27, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_BIG_PEARL
        [1186] = { layout = 236, x = 47, y = 30, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_PEARL
        [1187] = { layout = 236, x = 59, y = 32, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_NANAB_BERRY
        [1188] = { layout = 237, x = 8, y = 29, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE_RAWST_BERRY
        [1189] = { layout = 34, x = 2, y = 2, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_VIRIDIAN_CITY_GYM_MACHO_BRACE
        [1190] = { layout = 101, x = 58, y = 28, type = 2 }, -- hidden: FLAG_HIDDEN_ITEM_SSANNE_EXTERIOR_LAVA_COOKIE
        [1191] = { layout = 64, x = 33, y = 6, type = 0 }, -- field: FLAG_HIDE_CERULEAN_STORY_TM
    },
    floors = {
        [1] = "1F",
        [2] = "2F",
        [8] = "1F",
        [9] = "2F",
        [97] = "1F",
        [98] = "B1F",
        [99] = "B2F",
        [107] = "B1F",
        [108] = "1F",
        [109] = "2F",
        [110] = "3F",
        [111] = "B1F",
        [112] = "B2F",
        [113] = "B3F",
        [114] = "B4F",
        [115] = "1F",
        [116] = "2F",
        [117] = "3F",
        [118] = "4F",
        [119] = "5F",
        [120] = "6F",
        [121] = "7F",
        [122] = "8F",
        [123] = "9F",
        [124] = "10F",
        [125] = "11F",
        [126] = "1F",
        [127] = "2F",
        [128] = "3F",
        [129] = "B1F",
        [134] = "1F",
        [135] = "2F",
        [136] = "B1F",
        [137] = "1F",
        [138] = "B1F",
        [139] = "1F",
        [140] = "B1F",
        [141] = "B2F",
        [142] = "B3F",
        [143] = "B4F",
        [144] = "1F",
        [145] = "2F",
        [146] = "3F",
        [147] = "4F",
        [148] = "5F",
        [149] = "6F",
        [150] = "7F",
        [158] = "1F",
        [162] = "1F",
        [163] = "2F",
        [166] = "1F",
        [167] = "2F",
        [168] = "3F",
        [174] = "1F",
        [175] = "2F",
        [176] = "3F",
        [177] = "4F",
        [178] = "5F",
        [179] = "Roof",
        [194] = "1F",
        [202] = "2F",
        [205] = "1F",
        [206] = "1F",
        [208] = "1F",
        [209] = "2F",
        [251] = "B4F",
        [253] = "1F",
        [264] = "1F",
        [265] = "2F",
        [266] = "3F",
        [267] = "1F",
        [268] = "B1F",
        [269] = "B2F",
        [270] = "B3F",
        [273] = "B5F",
        [276] = "1F",
        [277] = "B1F",
        [280] = "1F",
        [281] = "2F",
        [282] = "3F",
        [283] = "4F",
        [284] = "5F",
        [285] = "6F",
        [286] = "7F",
        [287] = "8F",
        [291] = "1F",
        [292] = "B1F",
        [293] = "B2F",
        [294] = "B3F",
        [295] = "B4F",
        [298] = "2F",
        [326] = "1F",
        [329] = "2F",
        [330] = "3F",
        [331] = "4F",
        [332] = "5F",
        [333] = "B1F",
        [334] = "B2F",
        [335] = "B3F",
        [336] = "B4F",
        [337] = "B5F",
        [338] = "B6F",
        [339] = "B7F",
        [340] = "B8F",
        [341] = "B9F",
        [342] = "B10F",
        [343] = "B11F",
        [346] = "B1F",
    },
}
